import { transform } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { parse } from 'acorn';
const root = fileURLToPath(new URL('../../', import.meta.url));
const sdk = await readFile(resolve(root, 'packages/plugin-sdk/src/index.ts'), 'utf8');
const metadata = await readFile(resolve(root, 'packages/plugin-sdk/src/component-metadata.ts'), 'utf8');
const resources = await readFile(resolve(root, 'plugins/builtin-resources/src/index.ts'), 'utf8');
async function checkImports(name, source, allowed) {
  const { code } = await transform(source, { loader: 'ts', format: 'esm', target: 'node20' });
  const file = parse(code, { ecmaVersion: 'latest', sourceType: 'module' });
  const seen = [];
  function visit(node) {
    if (['ImportDeclaration', 'ExportNamedDeclaration', 'ExportAllDeclaration'].includes(node.type)) {
      if (node.source) {
        if (!allowed.includes(node.source.value)) throw new Error(`${name}: unexpected dependency`);
        seen.push(node.source.value);
      }
    }
    if (node.type === 'ImportExpression' || (node.type === 'CallExpression' && node.callee.type === 'Identifier' && ['require', '__require'].includes(node.callee.name))) {
      throw new Error(`${name}: dynamic dependencies are not allowed in the embedded bundle`);
    }
    for (const value of Object.values(node)) {
      if (Array.isArray(value)) value.forEach(child => { if (child?.type) visit(child); });
      else if (value?.type) visit(value);
    }
  }
  visit(file);
  if (seen.length !== allowed.length || allowed.some(name => !seen.includes(name))) throw new Error(`${name}: expected imports changed`);
}
await checkImports('SDK', sdk, ['node:readline']);
await checkImports('component metadata', metadata, []);
await checkImports('builtin resources', resources, ['../../../packages/plugin-sdk/src/index', '../../../packages/plugin-sdk/src/component-metadata']);
// The builtin imports only the SDK and its pure metadata. Concatenating them
// produces a self-contained file without resolving ancestor package directories.
const source = metadata + '\n' + sdk + '\n' + resources.replace(/^import .*from .*;\r?\n/gm, '');
await checkImports('combined bundle', source, ['node:readline']);
const { code } = await transform(source, { loader: 'ts', format: 'esm', target: 'node20', legalComments: 'none' });
const output = '// Generated by packages/plugin-sdk/build.mjs; do not edit.\n' + code;
const target = resolve(root, 'runtime/src/adapters/plugin/process/builtin.mjs');
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('Builtin plugin bundle is stale; run node packages/plugin-sdk/build.mjs');
} else await writeFile(target, output);
