import { MarkdownFilenameDialog } from "./MarkdownFilenameDialog";
import { inputNodeId, outputNodeId, record, resourceLabel, resourceKinds, type ResourceKind } from "./workflowResourceModel";
import {
  Background, BackgroundVariant, Handle, MarkerType, MiniMap, Panel, Position, ReactFlow, ReactFlowProvider,
  useNodesState, useReactFlow, type Connection, type Edge, type Node, type NodeProps, type NodeTypes, type XYPosition,
} from "@xyflow/react";
import { useEffect, useMemo, useState, type CSSProperties, type DragEvent, type KeyboardEvent } from "react";
import type { EditorGraph, EditorSelection, JsonObject, WorkflowLayout, WorkflowNodeType } from "./workflowEditorModel";
import { autoLayoutGraph, portColor, connectionError, GRAPH_NODE_HEADER_HEIGHT, GRAPH_PORT_ROW_HEIGHT, graphNodeHeight, graphNodeWidth, graphRunInputWidth, portKey, portLabel, preparePortLayout, type Port, type PortGraph } from "./workflowPortModel";

type CommonProps = { graph: EditorGraph; ports: PortGraph; onConnect(source: Port, target: Port): void; onFocus(nodeId: string, field?: string): void };
export function WorkflowPortConnections({ ports, onConnect, onFocus }: CommonProps) {
  const [sourceKey, setSource] = useState(""); const [targetKey, setTarget] = useState("");
  const sources = ports.ports.filter((port) => port.kind !== "execution" && port.direction === "output");
  const targets = ports.ports.filter((port) => port.kind === "data" && port.direction === "input");
  const source = sources.find((port) => portKey(port) === sourceKey), target = targets.find((port) => portKey(port) === targetKey);
  const error = source && target ? connectionError(source, target) : undefined;
  return <section className="workflow-port-connections" aria-label="Typed data bindings"><details><summary>Data bindings · {ports.edges.filter((edge) => edge.kind === "data").length}</summary>
    <form onSubmit={(event) => { event.preventDefault(); if (source && target && !error) onConnect(source, target); }}>
      <label>Data output<select value={source ? sourceKey : ""} onChange={(event) => setSource(event.target.value)}><option value="">Choose output</option>{sources.map((port) => <option key={portKey(port)} value={portKey(port)}>{portLabel(port)}</option>)}</select></label>
      <label>Data input<select value={target ? targetKey : ""} onChange={(event) => setTarget(event.target.value)}><option value="">Choose input</option>{targets.map((port) => <option key={portKey(port)} value={portKey(port)}>{portLabel(port)}</option>)}</select></label>
      <button className="button button--compact" type="submit" disabled={!source || !target || Boolean(error)}>Connect data ports</button>
    </form>{error && <p role="alert">{error}</p>}<p className="inspector-help">Reconnecting replaces the input source with the selected whole value. Configure pointers and remove bindings in the input inspector.</p>
    <ul>{ports.edges.filter((edge) => edge.kind === "data").map((edge) => <li key={edge.id}><button className="button button--compact" type="button" onClick={() => onFocus(edge.target.nodeId, `inputs.${edge.target.portId}`)}>{portLabel(edge.source)} → {portLabel(edge.target)}</button></li>)}</ul>
  </details>{ports.findings.length > 0 && <div role="status"><strong>{ports.findings.length} incomplete or invalid port connections</strong>{ports.findings.map((finding) => <button className="button button--compact port-finding" key={`${finding.nodeId}:${finding.field}`} type="button" onClick={() => onFocus(finding.nodeId, finding.field)}>{finding.nodeId}: {finding.code} — {finding.message}</button>)}</div>}</section>;
}

type PositionedPort = Port & { order?: number };
type WorkflowNodeData = { displayName: string; nodeType: string; checkpoint: string; status: string; capabilities: string; resource?:boolean; ports: Port[]; pending?: string; onChoose(port: Port): void; onFocus(): void };
type RunInputData = { title: string; kind: string; onFocus(): void; ports: Port[]; pending?: string; onChoose(port: Port): void };
type FlowNode = Node<WorkflowNodeData, "workflow"> | Node<RunInputData, "runInputs">;

function PortControl({ port, pending, onChoose }: { port: PositionedPort; pending?: string; onChoose(port: Port): void }) {
  const output = port.direction === "output"; const top = GRAPH_NODE_HEADER_HEIGHT + 17 + (port.order ?? 0) * GRAPH_PORT_ROW_HEIGHT;
  return <><Handle id={portKey(port)} type={output ? "source" : "target"} position={output ? Position.Right : Position.Left} className={`workflow-flow-handle workflow-flow-handle--${port.kind}${pending === portKey(port) ? " workflow-flow-handle--pending" : ""}`} style={{ top, background:portColor(port) }} title={portLabel(port)} />
    <button className={`workflow-flow-port nodrag nopan workflow-flow-port--${output ? "output" : "input"}`} style={{ top, "--port-color":portColor(port) } as CSSProperties} type="button" aria-label={`${port.direction} ${portLabel(port)}`} title={portLabel(port)} onClick={() => onChoose(port)}><span>{port.portId === "$new" ? "+ Input" : port.portId}</span>{port.kind === "data" || port.kind === "run_input" ? <small>{port.kind === "data" && port.portId === "$new" ? "" : port.valueType}{"required" in port && port.required ? " *" : ""}</small> : null}</button></>;
}
function WorkflowNodeCard({ data, selected }: NodeProps<Node<WorkflowNodeData, "workflow">>) {
  const left = data.ports.filter((port) => port.direction === "input"), right = data.ports.filter((port) => port.direction === "output");
  return <article className={`workflow-flow-node workflow-flow-node--${data.nodeType}${selected ? " workflow-flow-node--selected" : ""}`}>{data.resource && <Handle type="target" id="produced" position={Position.Left} style={{top:GRAPH_NODE_HEADER_HEIGHT+17,background:data.ports[0]?portColor(data.ports[0]):undefined}}/>}<button className="workflow-flow-node__body" type="button" onClick={data.onFocus} aria-label={`${data.displayName}, ${data.nodeType} node`}><span>{data.nodeType === "implementation" ? "Implementation · edits files" : data.nodeType.replaceAll("_", " ")}</span><strong>{data.displayName}</strong><small>{data.status === "Needs validation" ? data.status : data.resource ? data.capabilities : ""}</small></button>{left.map((port, order) => <PortControl key={portKey(port)} port={{ ...port, order }} pending={data.pending} onChoose={data.onChoose} />)}{right.map((port, order) => <PortControl key={portKey(port)} port={{ ...port, order }} pending={data.pending} onChoose={data.onChoose} />)}</article>;
}
function RunInputsCard({ data }: NodeProps<Node<RunInputData, "runInputs">>) { return <article className="workflow-flow-node workflow-flow-node--run-inputs workflow-flow-run-inputs"><button className="workflow-flow-node__body" onClick={data.onFocus}><span>{data.kind.replaceAll("_", " ")}</span><strong>{data.title}</strong></button>{data.ports.map((port, order) => <PortControl key={portKey(port)} port={{ ...port, order }} pending={data.pending} onChoose={data.onChoose} />)}</article>; }
const nodeTypes = { workflow: WorkflowNodeCard, runInputs: RunInputsCard } satisfies NodeTypes;

type CanvasProps = CommonProps & { document: JsonObject; onAddResource?(kind: ResourceKind, position: XYPosition, filename?: string): void; selection: EditorSelection; layout: WorkflowLayout; onSelect(selection: EditorSelection): void; onLayout(layout: JsonObject, message: string): void; readOnly?: boolean; onDropNode?(type: WorkflowNodeType, position: XYPosition): void };
type ConnectionMode = "all" | "execution" | "data";
function FlowCanvas({ document, onAddResource, graph, ports, selection, layout, onConnect, onFocus, onSelect, onLayout, onDropNode, readOnly = false }: CanvasProps) {
  const snapEnabled = layout.snapToGrid === true;
  const [markdownPosition,setMarkdownPosition]=useState<XYPosition>(); const flow = useReactFlow<FlowNode, Edge>(); const [pending, setPending] = useState<Port>(); const [message, setMessage] = useState(""); const connectionMode = "all" as ConnectionMode; const [menu, setMenu] = useState<{ x: number; y: number }>(); const [query, setQuery] = useState(""); const preparedLayout = useMemo(() => preparePortLayout(layout, graph, ports.ports), [graph, layout, ports.ports]);
  const portByKey = useMemo(() => new Map(ports.ports.map((port) => [portKey(port), port])), [ports.ports]);
  function choose(port: Port) { if (readOnly) return; if (port.direction === "output") { setPending(port); setMessage(`Choose an input for ${portLabel(port)}.`); return; } if (!pending) { if (port.kind !== "execution") onFocus(port.nodeId, `inputs.${port.portId}`); return; } const source = portByKey.get(portKey(pending)); if (!source) { setPending(undefined); setMessage("The source port no longer exists. Choose an output again."); return; } const error = connectionError(source, port); if (error) { setMessage(error); return; } onConnect(source, port); setPending(undefined); setMessage("Ports connected."); }
  const projectedNodes = useMemo<FlowNode[]>(() => {
    const result: FlowNode[] = graph.nodes.map((node) => ({ id: node.id, type: "workflow", position: preparedLayout.nodes[node.id] ?? node.position, selected: selection.kind === "node" && selection.nodeId === node.id, style: { width: graphNodeWidth(ports.ports, node), height: graphNodeHeight(ports.ports, node.id) }, data: { displayName: node.displayName, nodeType: node.type, checkpoint: node.checkpoint, status: node.validationCount || ports.findings.some((finding) => finding.nodeId === node.id) ? "Needs validation" : "Draft", capabilities: `${node.entry ? "Entry-capable " : ""}${node.terminal ? "Terminal-capable" : ""}`, ports: ports.ports.filter((port) => port.kind !== "run_input" && port.nodeId === node.id), pending: pending && portKey(pending), onChoose: choose, onFocus: () => onFocus(node.id) } }));
    const inputs = ports.ports.filter((port) => port.kind === "run_input");
    inputs.forEach((port,index) => {
      const id = inputNodeId(port.portId), declaration = record(record(record(document.spec).inputs)[port.portId]);
      const label = resourceLabel(port.portId, declaration);
      result.push({ id, type:"runInputs", position: preparedLayout.nodes[id] ?? {x:80,y:80+index*180}, selected:selection.kind === "node" && selection.nodeId === id, style:{width:280,height:150}, data:{title:label.title,kind:label.kind,ports:[port,...ports.ports.filter(p=>p.kind==="data"&&p.nodeId===id)],pending:pending && portKey(pending),onChoose:choose,onFocus:()=>onFocus(id)} });
    });
    for (const port of ports.ports) {
      if (port.kind !== "data" || port.direction !== "output") continue;
      const id = outputNodeId(port.nodeId,port.portId), owner=graph.nodes.find(n=>n.id===port.nodeId)!;
      const declaration=record(record(record(record(record(document.spec).nodes)[port.nodeId]).outputs)[port.portId]);
      const artifact=record(declaration.artifact); const position=preparedLayout.nodes[port.nodeId]??owner.position;
      const order=ports.ports.filter(p=>p.kind==="data" && p.nodeId===port.nodeId && p.direction==="output").findIndex(p=>p.portId===port.portId);
      result.push({id,type:"workflow",position:preparedLayout.nodes[id]??{x:position.x+graphNodeWidth(ports.ports,owner)+100,y:position.y+order*180},selected:selection.kind==="node"&&selection.nodeId===id,style:{width:280,height:210},data:{displayName:String(artifact.filename??port.portId),nodeType:artifact.filename?"artifact":port.valueType,checkpoint:"",status:"",capabilities:owner.type === "gate" && port.portId === "passed" ? "Controls True / False branches" : !record(record(record(document.spec).nodes)[port.nodeId]).transitions || (record(record(record(document.spec).nodes)[port.nodeId]).transitions as unknown[]).length === 0 ? "Final workflow result" : "",resource:true,ports:[port],pending:pending&&portKey(pending),onChoose:choose,onFocus:()=>onFocus(id)}});
    }
    const entry=String(record(record(document.spec).routeDefaults).entry), entryNode=graph.nodes.find(n=>n.id===entry);
    const entryPosition=entryNode?(preparedLayout.nodes[entry]??entryNode.position):{x:400,y:80};
    result.push({id:"$start",type:"workflow",position:preparedLayout.nodes.$start??{x:entryPosition.x,y:entryPosition.y-260},style:{width:240,height:150},data:{displayName:"Start",nodeType:"start",checkpoint:"",status:"",capabilities:"Run started",ports:[{kind:"execution",nodeId:"$start",portId:"complete",direction:"output"}],onChoose:choose,onFocus:()=>onSelect({kind:"none"})}});
    if (ports.ports.some(port => port.kind === "execution" && port.nodeId === "$done")) result.push({id:"$done",type:"workflow",position:preparedLayout.nodes.$done??{x:entryPosition.x+700,y:entryPosition.y},draggable:false,style:{width:240,height:150},data:{displayName:"Done",nodeType:"done",checkpoint:"",status:"",capabilities:"Default route completed",resource:false,ports:ports.ports.filter(port=>port.kind==="execution"&&port.nodeId==="$done"),onChoose:()=>setMessage("Done follows successful completion of a default terminal. Configure terminals in the node inspector."),onFocus:()=>setMessage("The daemon completes the run and work item when the selected route reaches a successful terminal. This endpoint shows the default route.")}});
    return result;
  }, [document, connectionMode, graph.nodes, onFocus, pending, ports.edges, ports.findings, ports.ports, preparedLayout.nodes]);
  const [nodes, setNodes, onNodesChange] = useNodesState<FlowNode>(projectedNodes); useEffect(() => setNodes(projectedNodes), [projectedNodes, setNodes]);
  useEffect(() => { if (preparedLayout.viewport) void flow.setViewport(preparedLayout.viewport); }, [preparedLayout.portLayoutSignature]);
  const edges = useMemo<Edge[]>(() => ports.edges.filter((edge) => connectionMode === "all" || edge.kind === connectionMode).map<Edge>((edge) => {
    const executionKind = edge.kind === "execution" ? graph.edges.find((item) => item.id === edge.id)?.kind : undefined;
    return { id: edge.id, label: edge.source.kind === "execution" && ["true","false"].includes(edge.source.portId) ? edge.source.portId === "true" ? "True" : "False" : undefined, labelStyle: { fill: "#e2e8f0" }, labelBgStyle: { fill: "#111c2a" }, source: edge.source.kind === "run_input" ? inputNodeId(edge.source.portId) : edge.source.kind === "data" ? outputNodeId(edge.source.nodeId,edge.source.portId) : edge.source.nodeId, target: edge.target.nodeId, sourceHandle: portKey(edge.source), targetHandle: portKey(edge.target), style: { "--port-color":portColor(edge.source) } as CSSProperties, markerEnd: { type: MarkerType.ArrowClosed, color:portColor(edge.source) }, type: "smoothstep", pathOptions: { borderRadius: 12, offset: executionKind === "bounded_repair" ? 64 : executionKind === "conditional" ? 32 : 20 }, zIndex: 0, className: `canvas-edge canvas-edge--${edge.kind}${executionKind ? ` canvas-edge--${executionKind}` : ""}${selection.kind === "edge" && selection.edgeId === edge.id ? " canvas-edge--selected" : ""}`, ariaLabel: `${edge.kind}: ${portLabel(edge.source)} to ${portLabel(edge.target)}` };
  }).concat(ports.ports.filter((port): port is Extract<Port,{kind:"data"}> => port.kind === "data" && port.direction === "output").map(port => ({id:"produce:"+port.nodeId+":"+port.portId,style:{"--port-color":portColor(port)} as CSSProperties,source:port.nodeId,target:outputNodeId(port.nodeId,port.portId),targetHandle:"produced",sourceHandle:portKey(port),type:"smoothstep",className:"canvas-edge canvas-edge--data"}))), [connectionMode, graph.edges, ports.edges, selection]);
  const validConnection = (connection: Connection | Edge) => { const source = connection.sourceHandle ? portByKey.get(connection.sourceHandle) : undefined, target = connection.targetHandle ? portByKey.get(connection.targetHandle) : undefined; return Boolean(source && target && !connectionError(source, target)); };
  function connect(connection: Connection) { if (readOnly) return; const source = connection.sourceHandle ? portByKey.get(connection.sourceHandle) : undefined, target = connection.targetHandle ? portByKey.get(connection.targetHandle) : undefined; if (!source || !target) { setMessage("Choose current typed ports before connecting."); return; } const error = connectionError(source, target); if (error) { setMessage(error); return; } onConnect(source, target); setPending(undefined); setMessage("Ports connected."); }
  function keyboard(event: KeyboardEvent<HTMLDivElement>) { if (event.target !== event.currentTarget) return; if (event.key === "Escape") { setPending(undefined); setMessage("Connection cancelled."); return; } if (!event.key.startsWith("Arrow")) return; event.preventDefault(); const dx = event.key === "ArrowLeft" ? -20 : event.key === "ArrowRight" ? 20 : 0, dy = event.key === "ArrowUp" ? -20 : event.key === "ArrowDown" ? 20 : 0; const node = selection.kind === "node" ? graph.nodes.find((candidate) => candidate.id === selection.nodeId) : undefined; if (event.shiftKey && node && !readOnly) onLayout({ ...layout, nodes: { ...layout.nodes, [node.id]: { x: node.position.x + dx, y: node.position.y + dy } } }, `Moved ${node.id}.`); else { const viewport = flow.getViewport(); void flow.setViewport({ ...viewport, x: viewport.x + dx, y: viewport.y + dy }); } }
  function drop(event: DragEvent<HTMLDivElement>) { const type = event.dataTransfer.getData("application/x-darkstar-workflow-node") as WorkflowNodeType; if (!type || !onDropNode) return; event.preventDefault(); onDropNode(type, flow.screenToFlowPosition({ x: event.clientX, y: event.clientY })); }
  return <div className="workflow-port-graph">{markdownPosition && <MarkdownFilenameDialog onCancel={()=>setMarkdownPosition(undefined)} onAdd={filename=>{onAddResource?.("artifact",markdownPosition,filename);setMarkdownPosition(undefined);}}/>}<p className="sr-only" role="status">{message}</p>{message && <p className="port-message">{message}</p>}<div className="workflow-canvas workflow-canvas--ports" tabIndex={0} aria-label="Workflow canvas. Drag nodes to arrange them, drag between compatible typed ports to connect them, use arrow keys to pan, or use Shift and arrow keys to move the selected node." onKeyDown={event => { if (!readOnly && event.target === event.currentTarget && (event.key === "Tab" || event.key === "Insert")) { event.preventDefault(); const rect=event.currentTarget.getBoundingClientRect(); setQuery(""); setMenu({x:rect.left+80,y:rect.top+80}); } else keyboard(event); }} onDragOver={(event) => { if (event.dataTransfer.types.includes("application/x-darkstar-workflow-node")) { event.preventDefault(); event.dataTransfer.dropEffect = "copy"; } }} onDrop={drop}>
    <ReactFlow<FlowNode, Edge> nodes={nodes} edges={edges} elevateEdgesOnSelect={false} nodeTypes={nodeTypes} onNodesChange={onNodesChange} snapToGrid={snapEnabled} snapGrid={[22, 22]} nodesDraggable={!readOnly} nodesConnectable={!readOnly} onPaneClick={() => { setMenu(undefined); onSelect({ kind: "none" }); }} onPaneContextMenu={event => { event.preventDefault(); if (!readOnly) { setQuery(""); setMenu({ x: event.clientX, y: event.clientY }); } }} onNodeClick={(_, node) => { if (node.id !== "$start" && node.id !== "$done") onFocus(node.id); }} onNodeDragStop={(_, node) => onLayout({ ...preparedLayout, nodes: { ...preparedLayout.nodes, [node.id]: { x: Math.round(node.position.x), y: Math.round(node.position.y) } } }, `Moved ${node.id}.`)} onEdgeClick={(_, edge) => { const portEdge = ports.edges.find((item) => item.id === edge.id); if (portEdge?.kind === "execution") onSelect({ kind: "edge", edgeId: edge.id }); else if (portEdge?.kind === "data") onFocus(portEdge.target.nodeId, `inputs.${portEdge.target.portId}`); }} onConnect={connect} isValidConnection={validConnection} defaultViewport={preparedLayout.viewport ?? { x: 24, y: 48, zoom: .85 }} minZoom={0.08} maxZoom={3} fitView={false} nodesFocusable={false} edgesFocusable>
      <Background variant={BackgroundVariant.Dots} gap={22} size={1} color="#273248" /><MiniMap ariaLabel="Workflow minimap" pannable zoomable nodeColor={(node) => node.selected ? "#8cb4ff" : "#456387"} maskColor="rgba(5, 9, 15, .7)" /><Panel position="top-left" className="port-canvas-toolbar" aria-label="Canvas controls"><button className="button button--compact nodrag" type="button" onClick={() => void flow.fitView({ padding: .16, minZoom: .08 })}>Zoom to fit</button><button className="button button--compact nodrag" type="button" aria-label="Zoom in" onClick={() => void flow.zoomIn()}>+</button><button className="button button--compact nodrag" type="button" aria-label="Zoom out" onClick={() => void flow.zoomOut()}>−</button><button className="button button--compact nodrag" type="button" onClick={() => { const next = autoLayoutGraph(preparedLayout, graph, ports.ports); onLayout(next, "Auto-layout applied; execution is unchanged."); void flow.setViewport(next.viewport!, { duration: 250 }); }}>Auto-layout</button>{pending && <button className="button button--compact nodrag" type="button" onClick={() => { setPending(undefined); setMessage("Connection cancelled."); }}>Cancel connection</button>}<button className="button button--compact nodrag" type="button" aria-label="Snap to grid" disabled={readOnly} aria-pressed={snapEnabled} onClick={() => onLayout({ ...preparedLayout, snapToGrid: !snapEnabled }, snapEnabled ? "Grid snapping off." : "Grid snapping on.")}>Snap: {snapEnabled ? "On" : "Off"}</button><span>{readOnly ? "Read only" : "Right-click to add a node"}</span></Panel>
    </ReactFlow>{menu && <div className="workflow-node-menu" role="dialog" aria-label="Add node" style={{ position: "fixed", left: Math.min(menu.x, window.innerWidth - 260), top: Math.min(menu.y, window.innerHeight - 360) }} onKeyDown={event => { if (event.key === "Escape") setMenu(undefined); }}><input autoFocus aria-label="Search nodes" placeholder="Search nodes…" value={query} onChange={event => setQuery(event.target.value)} />{resourceKinds.filter(kind => (kind === "artifact" ? "markdown file artifact" : kind).includes(query.toLowerCase())).map(kind => <button key={kind} onClick={() => { if(kind === "artifact")setMarkdownPosition(flow.screenToFlowPosition(menu));else onAddResource?.(kind,flow.screenToFlowPosition(menu)); setMenu(undefined); }}>{kind === "artifact" ? "Markdown file" : kind.replaceAll("_"," ")}</button>)}{(["workspace_prepare", "workspace_validate", "reasoning", "implementation", "gate", "command", "approval", "subworkflow", "point_execution", "routing"] as WorkflowNodeType[]).filter(type => type.includes(query.toLowerCase())).map(type => <button key={type} onClick={() => { onDropNode?.(type, flow.screenToFlowPosition(menu)); setMenu(undefined); }}>{type === "gate" ? "Branch / IF" : type.replaceAll("_", " ")}</button>)}</div>}</div></div>;
}
export function WorkflowPortCanvas(props: CanvasProps) { return <ReactFlowProvider><FlowCanvas {...props} /></ReactFlowProvider>; }
