import {
  Background, BackgroundVariant, Handle, MarkerType, MiniMap, Panel, Position, ReactFlow, ReactFlowProvider,
  useNodesState, useReactFlow, type Connection, type Edge, type Node, type NodeProps, type NodeTypes, type Viewport, type XYPosition,
} from "@xyflow/react";
import { useEffect, useMemo, useRef, useState, type DragEvent, type KeyboardEvent } from "react";
import type { EditorGraph, EditorSelection, JsonObject, WorkflowLayout, WorkflowNodeType } from "./workflowEditorModel";
import { autoLayoutGraph, connectionError, GRAPH_NODE_HEADER_HEIGHT, GRAPH_PORT_ROW_HEIGHT, graphNodeHeight, graphNodeWidth, graphRunInputWidth, portKey, portLabel, preparePortLayout, type Port, type PortGraph } from "./workflowPortModel";

type CommonProps = { graph: EditorGraph; ports: PortGraph; onConnect(source: Port, target: Port): void; onFocus(nodeId: string, field?: string): void };
export function WorkflowPortConnections({ ports, onConnect, onFocus }: CommonProps) {
  const [sourceKey, setSource] = useState(""); const [targetKey, setTarget] = useState("");
  const sources = ports.ports.filter((port) => port.kind !== "execution" && port.direction === "output");
  const targets = ports.ports.filter((port) => port.kind === "data" && port.direction === "input");
  const source = sources.find((port) => portKey(port) === sourceKey), target = targets.find((port) => portKey(port) === targetKey);
  const error = source && target ? connectionError(source, target) : undefined;
  return <section className="workflow-port-connections" aria-label="Typed data bindings"><details><summary>Data bindings · {ports.edges.filter((edge) => edge.kind === "data").length}</summary>
    <form onSubmit={(event) => { event.preventDefault(); if (source && target && !error) onConnect(source, target); }}>
      <label>Data output<select value={source ? sourceKey : ""} onChange={(event) => setSource(event.target.value)}><option value="">Choose output</option>{sources.map((port) => <option key={portKey(port)} value={portKey(port)}>{portLabel(port)}</option>)}</select></label>
      <label>Data input<select value={target ? targetKey : ""} onChange={(event) => setTarget(event.target.value)}><option value="">Choose input</option>{targets.map((port) => <option key={portKey(port)} value={portKey(port)}>{portLabel(port)}</option>)}</select></label>
      <button className="button button--compact" type="submit" disabled={!source || !target || Boolean(error)}>Connect data ports</button>
    </form>{error && <p role="alert">{error}</p>}<p className="inspector-help">Reconnecting replaces the input source with the selected whole value. Configure pointers and remove bindings in the input inspector.</p>
    <ul>{ports.edges.filter((edge) => edge.kind === "data").map((edge) => <li key={edge.id}><button className="button button--compact" type="button" onClick={() => onFocus(edge.target.nodeId, `inputs.${edge.target.portId}`)}>{portLabel(edge.source)} → {portLabel(edge.target)}</button></li>)}</ul>
  </details>{ports.findings.length > 0 && <div role="status"><strong>{ports.findings.length} incomplete or invalid port connections</strong>{ports.findings.map((finding) => <button className="button button--compact port-finding" key={`${finding.nodeId}:${finding.field}`} type="button" onClick={() => onFocus(finding.nodeId, finding.field)}>{finding.nodeId}: {finding.code} — {finding.message}</button>)}</div>}</section>;
}

type PositionedPort = Port & { order?: number };
type WorkflowNodeData = { displayName: string; nodeType: string; checkpoint: string; status: string; capabilities: string; ports: Port[]; pending?: string; onChoose(port: Port): void; onFocus(): void };
type RunInputData = { ports: Port[]; pending?: string; onChoose(port: Port): void };
type FlowNode = Node<WorkflowNodeData, "workflow"> | Node<RunInputData, "runInputs">;

function PortControl({ port, pending, onChoose }: { port: PositionedPort; pending?: string; onChoose(port: Port): void }) {
  const output = port.direction === "output"; const top = port.kind === "run_input" ? 58 + (port.order ?? 0) * GRAPH_PORT_ROW_HEIGHT : GRAPH_NODE_HEADER_HEIGHT + 17 + (port.order ?? 0) * GRAPH_PORT_ROW_HEIGHT;
  return <><Handle id={portKey(port)} type={output ? "source" : "target"} position={output ? Position.Right : Position.Left} className={`workflow-flow-handle workflow-flow-handle--${port.kind}${pending === portKey(port) ? " workflow-flow-handle--pending" : ""}`} style={top === undefined ? undefined : { top }} title={portLabel(port)} />
    <button className={`workflow-flow-port nodrag nopan workflow-flow-port--${output ? "output" : "input"}`} style={top === undefined ? undefined : { top }} type="button" aria-label={`${port.direction} ${portLabel(port)}`} title={portLabel(port)} onClick={() => onChoose(port)}><span>{port.portId}</span>{port.kind === "data" || port.kind === "run_input" ? <small>{port.valueType}{"required" in port && port.required ? " *" : ""}</small> : null}</button></>;
}
function WorkflowNodeCard({ data, selected }: NodeProps<Node<WorkflowNodeData, "workflow">>) {
  const left = data.ports.filter((port) => port.direction === "input"), right = data.ports.filter((port) => port.direction === "output");
  return <article className={`workflow-flow-node workflow-flow-node--${data.nodeType}${selected ? " workflow-flow-node--selected" : ""}`}><button className="workflow-flow-node__body" type="button" onClick={data.onFocus} aria-label={`${data.displayName}, ${data.nodeType} node`}><span>{data.nodeType.replaceAll("_", " ")}</span><strong>{data.displayName}</strong><small>{data.checkpoint} checkpoint · {data.status}</small><i>{data.capabilities}</i></button>{left.map((port, order) => <PortControl key={portKey(port)} port={{ ...port, order }} pending={data.pending} onChoose={data.onChoose} />)}{right.map((port, order) => <PortControl key={portKey(port)} port={{ ...port, order }} pending={data.pending} onChoose={data.onChoose} />)}</article>;
}
function RunInputsCard({ data }: NodeProps<Node<RunInputData, "runInputs">>) { return <article className="workflow-flow-node workflow-flow-node--run-inputs workflow-flow-run-inputs"><strong>Run inputs</strong>{data.ports.map((port, order) => <PortControl key={portKey(port)} port={{ ...port, order }} pending={data.pending} onChoose={data.onChoose} />)}</article>; }
const nodeTypes = { workflow: WorkflowNodeCard, runInputs: RunInputsCard } satisfies NodeTypes;

type CanvasProps = CommonProps & { selection: EditorSelection; layout: WorkflowLayout; onSelect(selection: EditorSelection): void; onLayout(layout: JsonObject, message: string): void; onDropNode?(type: WorkflowNodeType, position: XYPosition): void };
function FlowCanvas({ graph, ports, selection, layout, onConnect, onFocus, onSelect, onLayout, onDropNode }: CanvasProps) {
  const flow = useReactFlow<FlowNode, Edge>(); const [pending, setPending] = useState<Port>(); const [message, setMessage] = useState(""); const [showDataEdges, setShowDataEdges] = useState(false); const preparedLayout = useMemo(() => preparePortLayout(layout, graph, ports.ports), [graph, layout, ports.ports]); const requiresLayoutMigration = preparedLayout !== layout; const skipInitialFit = useRef(false);
  const portByKey = useMemo(() => new Map(ports.ports.map((port) => [portKey(port), port])), [ports.ports]);
  useEffect(() => { if (requiresLayoutMigration) onLayout(preparedLayout, "Canvas layout updated for readable node dimensions."); }, [onLayout, preparedLayout, requiresLayoutMigration]);
  function choose(port: Port) { if (port.direction === "output") { setPending(port); setMessage(`Choose an input for ${portLabel(port)}.`); return; } if (!pending) { if (port.kind !== "execution") onFocus(port.nodeId, `inputs.${port.portId}`); return; } const source = portByKey.get(portKey(pending)); if (!source) { setPending(undefined); setMessage("The source port no longer exists. Choose an output again."); return; } const error = connectionError(source, port); if (error) { setMessage(error); return; } onConnect(source, port); setPending(undefined); setMessage("Ports connected."); }
  const projectedNodes = useMemo<FlowNode[]>(() => {
    const result: FlowNode[] = graph.nodes.map((node) => ({ id: node.id, type: "workflow", position: preparedLayout.nodes[node.id] ?? node.position, selected: selection.kind === "node" && selection.nodeId === node.id, style: { width: graphNodeWidth(ports.ports, node), height: graphNodeHeight(ports.ports, node.id) }, data: { displayName: node.displayName, nodeType: node.type, checkpoint: node.checkpoint, status: node.validationCount || ports.findings.some((finding) => finding.nodeId === node.id) ? "Needs validation" : "Draft", capabilities: `${node.entry ? "Entry-capable " : ""}${node.terminal ? "Terminal-capable" : ""}`, ports: ports.ports.filter((port) => port.kind !== "run_input" && port.nodeId === node.id), pending: pending && portKey(pending), onChoose: choose, onFocus: () => onFocus(node.id) } }));
    const inputs = ports.ports.filter((port) => port.kind === "run_input"); if (inputs.length) result.unshift({ id: "__run_inputs__", type: "runInputs", position: { x: 80, y: 80 }, draggable: false, selectable: false, style: { width: graphRunInputWidth(ports.ports), height: 84 + inputs.length * 38 }, data: { ports: inputs, pending: pending && portKey(pending), onChoose: choose } }); return result;
  }, [graph.nodes, onFocus, pending, ports.findings, ports.ports, preparedLayout.nodes]);
  const [nodes, setNodes, onNodesChange] = useNodesState<FlowNode>(projectedNodes); useEffect(() => setNodes(projectedNodes), [projectedNodes, setNodes]);
  const edges = useMemo<Edge[]>(() => ports.edges.filter((edge) => edge.kind === "execution" || showDataEdges).map((edge) => ({ id: edge.id, source: edge.source.kind === "run_input" ? "__run_inputs__" : edge.source.nodeId, target: edge.target.nodeId, sourceHandle: portKey(edge.source), targetHandle: portKey(edge.target), markerEnd: { type: MarkerType.ArrowClosed }, className: `canvas-edge canvas-edge--${edge.kind}${edge.kind === "execution" ? ` canvas-edge--${graph.edges.find((item) => item.id === edge.id)?.kind}` : ""}${selection.kind === "edge" && selection.edgeId === edge.id ? " canvas-edge--selected" : ""}`, ariaLabel: `${edge.kind}: ${portLabel(edge.source)} to ${portLabel(edge.target)}` })), [graph.edges, ports.edges, selection, showDataEdges]);
  const validConnection = (connection: Connection | Edge) => { const source = connection.sourceHandle ? portByKey.get(connection.sourceHandle) : undefined, target = connection.targetHandle ? portByKey.get(connection.targetHandle) : undefined; return Boolean(source && target && !connectionError(source, target)); };
  function connect(connection: Connection) { const source = connection.sourceHandle ? portByKey.get(connection.sourceHandle) : undefined, target = connection.targetHandle ? portByKey.get(connection.targetHandle) : undefined; if (!source || !target) { setMessage("Choose current typed ports before connecting."); return; } const error = connectionError(source, target); if (error) { setMessage(error); return; } onConnect(source, target); setPending(undefined); setMessage("Ports connected."); }
  function keyboard(event: KeyboardEvent<HTMLDivElement>) { if (event.target !== event.currentTarget) return; if (event.key === "Escape") { setPending(undefined); setMessage("Connection cancelled."); return; } if (!event.key.startsWith("Arrow")) return; event.preventDefault(); const dx = event.key === "ArrowLeft" ? -20 : event.key === "ArrowRight" ? 20 : 0, dy = event.key === "ArrowUp" ? -20 : event.key === "ArrowDown" ? 20 : 0; const node = selection.kind === "node" ? graph.nodes.find((candidate) => candidate.id === selection.nodeId) : undefined; if (event.shiftKey && node) onLayout({ ...layout, nodes: { ...layout.nodes, [node.id]: { x: node.position.x + dx, y: node.position.y + dy } } }, `Moved ${node.id}.`); else { const viewport = flow.getViewport(); void flow.setViewport({ ...viewport, x: viewport.x + dx, y: viewport.y + dy }); } }
  function drop(event: DragEvent<HTMLDivElement>) { const type = event.dataTransfer.getData("application/x-darkstar-workflow-node") as WorkflowNodeType; if (!type || !onDropNode) return; event.preventDefault(); onDropNode(type, flow.screenToFlowPosition({ x: event.clientX, y: event.clientY })); }
  return <div className="workflow-port-graph"><p className="sr-only" role="status">{message}</p>{message && <p className="port-message">{message}</p>}<div className="workflow-canvas workflow-canvas--ports" tabIndex={0} aria-label="Workflow canvas. Drag nodes to arrange them, drag between compatible typed ports to connect them, use arrow keys to pan, or use Shift and arrow keys to move the selected node." onKeyDown={keyboard} onDragOver={(event) => { if (event.dataTransfer.types.includes("application/x-darkstar-workflow-node")) { event.preventDefault(); event.dataTransfer.dropEffect = "copy"; } }} onDrop={drop}>
    <ReactFlow<FlowNode, Edge> nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onNodeClick={(_, node) => { if (node.type === "workflow") onFocus(node.id); }} onNodeDragStop={(_, node) => onLayout({ ...preparedLayout, nodes: { ...preparedLayout.nodes, [node.id]: { x: Math.round(node.position.x), y: Math.round(node.position.y) } } }, `Moved ${node.id}.`)} onEdgeClick={(_, edge) => { const portEdge = ports.edges.find((item) => item.id === edge.id); if (portEdge?.kind === "execution") onSelect({ kind: "edge", edgeId: edge.id }); else if (portEdge?.kind === "data") onFocus(portEdge.target.nodeId, `inputs.${portEdge.target.portId}`); }} onConnect={connect} isValidConnection={validConnection} defaultViewport={preparedLayout.viewport ?? { x: 24, y: 48, zoom: .85 }} minZoom={0.25} maxZoom={3} onMoveEnd={(_, viewport: Viewport) => { if (skipInitialFit.current) { skipInitialFit.current = false; return; } onLayout({ ...preparedLayout, viewport }, "Updated canvas view."); }} fitView={false} nodesFocusable={false} edgesFocusable>
      <Background variant={BackgroundVariant.Dots} gap={22} size={1} color="#273248" /><MiniMap ariaLabel="Workflow minimap" pannable zoomable nodeColor={(node) => node.selected ? "#8cb4ff" : "#456387"} maskColor="rgba(5, 9, 15, .7)" /><Panel position="top-left" className="port-canvas-toolbar" aria-label="Canvas controls"><button className="button button--compact nodrag" type="button" onClick={() => void flow.fitView({ padding: .25 })}>Zoom to fit</button><button className="button button--compact nodrag" type="button" aria-label="Zoom in" onClick={() => void flow.zoomIn()}>+</button><button className="button button--compact nodrag" type="button" aria-label="Zoom out" onClick={() => void flow.zoomOut()}>−</button><button className="button button--compact nodrag" type="button" onClick={() => { const next = autoLayoutGraph(preparedLayout, graph, ports.ports); onLayout(next, "Auto-layout applied; execution is unchanged."); void flow.setViewport(next.viewport!, { duration: 250 }); }}>Auto-layout</button><button className="button button--compact nodrag" type="button" aria-pressed={showDataEdges} onClick={() => setShowDataEdges((shown) => !shown)}>{showDataEdges ? "Hide data bindings" : `Show data bindings · ${ports.edges.filter((edge) => edge.kind === "data").length}`}</button>{pending && <button className="button button--compact nodrag" type="button" onClick={() => { setPending(undefined); setMessage("Connection cancelled."); }}>Cancel connection</button>}<span>Execution paths stay visible. Data bindings are dashed when shown.</span></Panel>
    </ReactFlow></div></div>;
}
export function WorkflowPortCanvas(props: CanvasProps) { return <ReactFlowProvider><FlowCanvas {...props} /></ReactFlowProvider>; }
