import { build } from '../../packages/plugin-sdk/node_modules/esbuild/lib/main.js';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, relative } from 'node:path';
import { parse } from '../../packages/plugin-sdk/node_modules/acorn/dist/acorn.mjs';

const root = fileURLToPath(new URL('../../', import.meta.url));
const allowed = new Set([
  'packages/plugin-sdk/src/index.ts',
  ...['index', 'shared', 'reasoning', 'implementation', 'point-execution', 'command', 'workspace-prepare', 'workspace-validate'].map(name => {
    return `plugins/builtin-nodes/src/${name}.ts`;
  })
]);
const result = await build({
  absWorkingDir: root,
  entryPoints: ['plugins/builtin-nodes/src/index.ts'],
  bundle: true,
  write: false,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'none',
  plugins: [{
    name: 'pinned-node-dependencies',
    setup(builder) {
      builder.onResolve({ filter: /.*/ }, args => {
        if (args.kind === 'dynamic-import' || args.kind === 'require-call') {
          throw new Error('Dynamic node dependencies cannot be digest pinned');
        }
        if (args.path === 'node:readline') {
          if (relative(root, args.importer).replaceAll('\\', '/') !== 'packages/plugin-sdk/src/index.ts') {
            throw new Error('Only the SDK may import protocol I/O');
          }
          return { path: args.path, external: true };
        }
        const path = resolve(args.resolveDir || root, args.path);
        const candidate = path.endsWith('.ts') ? path : `${path}.ts`;
        if (!allowed.has(relative(root, candidate).replaceAll('\\', '/'))) {
          throw new Error(`Unexpected builtin node dependency: ${args.path}`);
        }
        return { path: candidate };
      });
    }
  }]
});

// Every application module must be bundled inside the implementation digest.
const code = result.outputFiles[0].text;
const tree = parse(code, { ecmaVersion: 'latest', sourceType: 'module' });
function visit(node) {
  if (['ImportDeclaration', 'ExportNamedDeclaration', 'ExportAllDeclaration'].includes(node.type) && node.source && node.source.value !== 'node:readline') {
    throw new Error('Unbundled node dependency');
  }
  if (node.type === 'ImportExpression' || (node.type === 'CallExpression' && node.callee.type === 'Identifier' && ['require', '__require'].includes(node.callee.name))) {
    throw new Error('Dynamic node dependencies cannot be digest pinned');
  }
  for (const value of Object.values(node)) {
    if (Array.isArray(value)) {
      for (const child of value) {
        if (child?.type) {
          visit(child);
        }
      }
    } else if (value?.type) {
      visit(value);
    }
  }
}
visit(tree);
const output = '// Generated by plugins/builtin-nodes/build.mjs; do not edit.\n' + code;
const target = new URL('../../runtime/src/adapters/nodeextension/typescript/builtin.mjs', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) {
    throw new Error('Builtin nodes bundle is stale');
  }
} else {
  await writeFile(target, output);
}
