// Generated by plugins/builtin-nodes/build.mjs; do not edit.
// packages/plugin-sdk/src/index.ts
import { createInterface } from "node:readline";
var protocol = "darkstar.plugin/v1";
function serve(plugin) {
  const pending = /* @__PURE__ */ new Map();
  let sequence = 0;
  const send = (message) => {
    return process.stdout.write(JSON.stringify(message) + "\n");
  };
  const host = {
    call(method, arguments_) {
      const id = `host-${++sequence}`;
      return new Promise((resolve, reject) => {
        pending.set(id, {
          resolve,
          reject
        });
        send({
          type: "host_call",
          id,
          method,
          params: arguments_
        });
      });
    }
  };
  const lines = createInterface({
    input: process.stdin,
    crlfDelay: Infinity
  });
  lines.on("line", async (line) => {
    let request;
    try {
      request = JSON.parse(line);
      if (request.type === "host_result") {
        const waiter = pending.get(request.id);
        if (!waiter) {
          throw new Error("Unknown host result");
        }
        pending.delete(request.id);
        request.error ? waiter.reject(new Error(request.error)) : waiter.resolve(request.result);
        return;
      }
      if (request.type !== "request") {
        throw new Error("Invalid request type");
      }
      let result;
      if (request.method === "describe") {
        result = {
          protocol,
          ref: {
            id: plugin.id,
            version: plugin.version
          },
          resources: plugin.resources,
          tools: plugin.tools ?? [],
          ...plugin.nodes ? {
            nodes: plugin.nodes
          } : {}
        };
      } else {
        if (request.method === "invoke") {
          const tool = [...plugin.resources.map((resource) => {
            return resource.tool;
          }), ...plugin.tools ?? [], ...plugin.nodes ?? []].find((tool2) => {
            return tool2.id === request.params.contribution;
          });
          if (!tool) {
            throw new Error("Unknown contribution");
          }
          result = await tool.invoke(request.params.arguments, host);
        } else {
          throw new Error("Unknown method");
        }
      }
      send({
        type: "response",
        id: request.id,
        result
      });
    } catch (error) {
      send({
        type: "response",
        id: request?.id ?? "",
        error: error instanceof Error ? error.message : String(error)
      });
    }
  });
}

// plugins/builtin-nodes/src/shared.ts
var changeset = () => {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      summary: {
        type: "string"
      },
      files: {
        type: "array",
        items: {
          type: "string"
        }
      },
      validation: {
        type: "array",
        items: {
          type: "string"
        }
      }
    },
    required: ["summary", "files", "validation"]
  };
};
function writable(permissions = []) {
  if (JSON.stringify([...permissions].sort()) !== JSON.stringify(["process.run", "workspace.write"])) {
    throw new Error("workspace node requires exactly process.run and workspace.write permissions");
  }
}
function defineNode(id, requiredCapabilities, behavior) {
  return {
    id,
    description: `Built-in ${id} node behavior`,
    requiredCapabilities,
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        operation: {
          enum: ["buildTask", "configureOutputs", "execute"]
        },
        configuration: {
          type: "object"
        },
        permissions: {
          type: "array",
          items: {
            type: "string"
          }
        },
        properties: {
          type: "object"
        },
        inputs: {
          type: "object"
        }
      },
      required: ["operation", "configuration"]
    },
    resultSchema: {
      type: "object"
    },
    invoke: async (arguments_, host) => {
      const args = arguments_;
      if (args.operation === "buildTask") {
        if (!behavior.buildTask) {
          throw new Error("node does not build agent tasks");
        }
        return behavior.buildTask(args);
      }
      if (args.operation === "configureOutputs") {
        if (!behavior.configureOutputs) {
          throw new Error("node does not configure agent outputs");
        }
        return behavior.configureOutputs(args);
      }
      if (args.operation !== "execute") {
        throw new Error("unknown node operation");
      }
      if (!behavior.execute) {
        throw new Error("node does not execute deterministic work");
      }
      return behavior.execute(args, host);
    }
  };
}

// plugins/builtin-nodes/src/reasoning.ts
var reasoning = defineNode("reasoning", [], {
  buildTask: (args) => {
    const c = args.configuration;
    if (args.permissions?.length) {
      throw new Error("workflow node names permission policies that are not configured: " + args.permissions.join(", "));
    }
    return {
      agent: c.agent,
      instructions: "Complete the following task using only the supplied inputs. " + (c.instructions ?? ""),
      skills: c.skills ?? [],
      tools: c.tools ?? [],
      access: "read_only"
    };
  },
  configureOutputs: (args) => {
    return structuredClone(args.properties ?? {});
  }
});

// plugins/builtin-nodes/src/implementation.ts
var implementationInstructions = (c) => {
  return "Implement the task in the connected input " + c.taskInput + " in the supplied workspace. Read optional connected Markdown instructions and supporting inputs when present; a plan is not required. Modify the actual files and run relevant checks. Preserve unrelated work. Do not commit, push, publish, or deploy. Use inspect_workspace_changes to see file changes relative to this attempt's durable baseline. Return changeset with disposition (changed, unchanged, or blocked), summary, files (exact relative paths reported by inspect_workspace_changes), and validation (checks actually run and results). Use unchanged only if the request is already satisfied and no files changed. Use blocked to report a blocker; blocked is not a successful completion. The runtime verifies files against the workspace; merely returning proposed content does not implement the task. " + (c.instructions ?? "");
};
var implementation = defineNode("implementation", [], {
  buildTask: (args) => {
    writable(args.permissions);
    return {
      agent: "implementation",
      instructions: implementationInstructions(args.configuration),
      skills: [],
      tools: [],
      access: "workspace_write"
    };
  },
  configureOutputs: (args) => {
    const properties = structuredClone(args.properties ?? {});
    if (Object.hasOwn(properties, "changeset")) {
      const schema = changeset();
      schema.properties.disposition = {
        type: "string",
        enum: ["changed", "unchanged", "blocked"]
      };
      schema.required.unshift("disposition");
      properties.changeset = schema;
    }
    return properties;
  }
});

// plugins/builtin-nodes/src/point-execution.ts
var pointInstructions = "Read the connected Markdown implementation plan and carry out its points. Implement the requested work item in the supplied workspace. Make only the necessary repository changes. Do not claim completion unless the requested outcome exists on disk. Return changeset with summary, files, and validation; return progress with completed_points and remaining_points.";
var pointExecution = defineNode("point-execution", [], {
  buildTask: (args) => {
    writable(args.permissions);
    return {
      agent: "implementation-point",
      instructions: pointInstructions,
      skills: [],
      tools: [],
      access: "workspace_write"
    };
  },
  configureOutputs: (args) => {
    const properties = structuredClone(args.properties ?? {});
    if (Object.hasOwn(properties, "changeset")) {
      const schema = changeset();
      properties.changeset = schema;
    }
    if (Object.hasOwn(properties, "progress")) {
      properties.progress = {
        type: "object",
        additionalProperties: false,
        properties: {
          completed_points: {
            type: "integer"
          },
          remaining_points: {
            type: "integer"
          }
        },
        required: ["completed_points", "remaining_points"]
      };
    }
    return properties;
  }
});

// plugins/builtin-nodes/src/workspace-prepare.ts
var workspacePrepare = defineNode("workspace-prepare", ["workspace.prepare"], {
  execute: async (args, host) => {
    const c = args.configuration;
    if (!["current_checkout", "new_worktree"].includes(c.checkout?.mode)) {
      throw new Error("choose a supported checkout mode");
    }
    if (!args.inputs || !Object.hasOwn(args.inputs, c.repositoryInput)) {
      throw new Error("connect the repository input to Prepare workspace");
    }
    const workspace = await host.call("workspace.prepare", {
      repository: args.inputs[c.repositoryInput],
      checkout: c.checkout
    });
    return {
      workspace
    };
  }
});

// plugins/builtin-nodes/src/workspace-validate.ts
var workspaceValidate = defineNode("workspace-validate", ["workspace.resolve", "process.run"], {
  execute: async (args, host) => {
    const c = args.configuration;
    if (!c.checks?.length) {
      throw new Error("at least one required check must be configured");
    }
    const workspace = await host.call("workspace.resolve", {
      reference: args.inputs?.[c.workspaceInput]
    });
    const checks = [];
    for (const argv of c.checks) {
      if (!argv.length || !argv[0].trim()) {
        throw new Error("validation check requires an executable");
      }
      const output = await host.call("process.run", {
        argv,
        timeoutSeconds: 120
      });
      checks.push({
        argv,
        exitCode: 0,
        output
      });
    }
    return {
      validation: {
        workspaceId: workspace.id,
        passed: true,
        checks
      }
    };
  }
});

// plugins/builtin-nodes/src/command.ts
var command = defineNode("command", ["process.run"], {
  execute: async (args, host) => {
    const c = args.configuration;
    if (JSON.stringify(c.argv) !== JSON.stringify(["darkstar-project", "validate", "--json"]) || c.cwd) {
      throw new Error("command node is not an explicitly supported deterministic builtin");
    }
    const timeoutSeconds = Math.min(c.timeoutSeconds ?? 30, 30);
    await host.call("process.run", {
      check: "diff",
      timeoutSeconds
    });
    const output = await host.call("process.run", {
      check: "status",
      timeoutSeconds
    });
    const changedEntries = output.trim() ? output.trim().split(/\s+/u).length : 0;
    if (!changedEntries) {
      throw new Error("darkstar-project validation found no repository changes for the requested implementation");
    }
    return {
      validation: {
        passed: true,
        acceptanceCovered: true,
        checks: [{
          command: "git diff --check HEAD",
          passed: true
        }, {
          command: "git status --porcelain",
          passed: true,
          changedEntries
        }]
      }
    };
  }
});

// plugins/builtin-nodes/src/index.ts
serve({
  id: "darkstar/builtin-nodes",
  version: "1.0.0",
  resources: [],
  nodes: [reasoning, implementation, pointExecution, workspacePrepare, workspaceValidate, command]
});
