import { transform } from '../../packages/plugin-sdk/node_modules/esbuild/lib/main.js';
import { parse } from '../../packages/plugin-sdk/node_modules/acorn/dist/acorn.mjs';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
const source = fileURLToPath(new URL('./src/index.ts', import.meta.url));
const sdk = fileURLToPath(new URL('../../packages/plugin-sdk/src/provider.ts', import.meta.url));
const combined = await readFile(sdk, 'utf8') + '\n' + (await readFile(source, 'utf8')).replace(/^import .*from '\.\.\/\.\.\/\.\.\/packages\/plugin-sdk\/src\/provider';\r?\n/m, '');
const { code } = await transform(combined, { loader: 'ts', format: 'esm', target: 'node20', legalComments: 'none' });
// No unresolved application dependencies may sit outside the pinned bundle.
const tree = parse(code, { ecmaVersion: 'latest', sourceType: 'module' });
function visit(node) {
  if (['ImportDeclaration', 'ExportNamedDeclaration', 'ExportAllDeclaration'].includes(node.type) && node.source && !node.source.value.startsWith('node:')) throw new Error('Unpinned provider dependency');
  if (node.type === 'ImportExpression' || (node.type === 'CallExpression' && node.callee.type === 'Identifier' && ['require', '__require'].includes(node.callee.name))) throw new Error('Dynamic provider dependencies cannot be digest pinned');
  for (const value of Object.values(node)) {
    if (Array.isArray(value)) value.forEach(child => { if (child?.type) visit(child); });
    else if (value?.type) visit(value);
  }
}
visit(tree);
const output = '// Generated by plugins/provider-codex/build.mjs; do not edit.\n' + code;
const target = fileURLToPath(new URL('../../runtime/src/adapters/provider/typescript/builtin.mjs', import.meta.url));
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('Builtin provider bundle is stale');
} else {
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output);
}
