import { test, expect } from '@playwright/test';
import { installEmptyControlPlane } from './acceptance.fixtures';

test.use({ timezoneId: 'UTC' });

test('run offers a scrubbed transcript, turn count, artifacts, inline decisions and live messages', async ({ page }, testInfo) => {
 await page.setViewportSize({ width: 1600, height: 1100 }); await installEmptyControlPlane(page);
 const runId='run_01K3Z1C2AAAAAAAAAAAAAAAAAA', workId='work_01K3Z1C2AAAAAAAAAAAAAAAAAA', start='2026-09-08T17:00:00Z';
 const run={id:runId,workItemId:workId,workflowId:'single-shot',workflowVersion:'1.0.1',status:'running',resourceVersion:4,createdAt:start,updatedAt:'2026-09-08T17:01:00Z'};
 const work={id:workId,title:'Update the README in a new worktree',status:'in_progress',projectId:'project-test',resourceVersion:3,createdAt:start,updatedAt:start};
 const view={run,nodes:[],attempts:[{id:'attempt-a',runId,nodeId:'implement',status:'running',provider:'codex',createdAt:start,updatedAt:start}],timeline:[],commands:[],timelinePageInfo:{hasEarlier:false},commandsPageInfo:{hasEarlier:false}};
 await page.route(`**/api/v1/runs/${runId}`,r=>r.fulfill({json:view}));
 await page.route(`**/api/v1/work-items/${workId}`,r=>r.fulfill({json:{work,runs:[run],stories:[]}}));
 await page.route('**/api/v1/work-items/*/transition-plan**',r=>r.fulfill({json:{resourceVersion:3,state:'running',targets:[]}}));
 const event=(position:number,method:string,params:any)=>({position,time:new Date(Date.parse(start)+position*1000).toISOString(),kind:'attempt.provider_event',subject:'attempt-a',data:{payload:{providerMethod:method,params}}});
 const events=[event(1,'turn/started',{turn:{id:'turn-a'}}),event(2,'item/completed',{item:{type:'agentMessage',id:'message-a',text:'I’ll inspect the project, update the README, and run the relevant checks.'}}),event(10,'item/completed',{item:{type:'commandExecution',id:'cmd',command:'git status --short\ngo test ./...',aggregatedOutput:'ok  darkstar/src/core/workflow\nok  darkstar/src/api',exitCode:0}}),event(20,'item/reasoning/summaryTextDelta',{itemId:'reason',delta:'The tests passed. I am checking the documentation against the actual commands.'}),event(30,'thread/tokenUsage/updated',{threadId:'thread-a',tokenUsage:{total:{inputTokens:3200,outputTokens:1800,reasoningOutputTokens:450}}}),event(40,'item/completed',{item:{type:'agentMessage',id:'message-b',text:JSON.stringify({research:'The README now covers installation, workflows, and running the daemon.\n\n## Verification\n\n**Passed** with `go test`.\n\n| Check | Result |\n| --- | --- |\n| Unit | Passed |\n\n```powershell\ngo test ./...\n```\n\n[Unsafe](javascript:alert(1))',design:'# Design artifact\n\nReadable content.'})}})];
 await page.route(`**/api/v1/runs/${runId}/transcript?**`,r=>r.fulfill({json:{events:events.filter(e=>e.position>Number(new URL(r.request().url()).searchParams.get('after')??0)),next:40,hasMore:false}}));
 await page.route(`**/api/v1/runs/${runId}/artifacts?**`,r=>r.fulfill({json:{records:new URL(r.request().url()).searchParams.get('after')==='0'?[{sequence:1,attemptId:'attempt-a',resource:'output:workspace:README.md',entryId:'README.md',operation:'snapshot',content:JSON.stringify('# DARKSTAR\n\nA local workflow engine.\n\n## Installation\n\nRun the setup command.')},{sequence:2,attemptId:'attempt-a',resource:'decisions',entryId:'d1',operation:'record',content:'Keep installation instructions next to the quick start.'},{sequence:3,attemptId:'attempt-a',resource:'open',entryId:'o1',operation:'add',content:'Confirm the Windows prerequisite versions.'}]:[],next:3,hasMore:false}}));
 let reviewed=false;const decision={kind:'workflow_control',id:'approval_01K3Z1C2AAAAAAAAAAAAAAAAAA',context:{runId,workItemId:workId,workTitle:work.title,projectId:'p',projectName:'DARKSTAR'},summary:'Review implementation',subject:{nodeId:'implement',visitId:'visit-a',attemptId:'attempt-a',scopeDigest:'a'.repeat(64),policyDigest:'b'.repeat(64)},allowedActions:['approve','deny','cancel'],resourceVersion:1,createdAt:start,updatedAt:start,urgency:1};
 await page.route('**/api/v1/attention/v2?**',r=>r.fulfill({json:{schemaVersion:2,items:reviewed?[]:[decision],totalCount:reviewed?0:1}}));
 await page.route('**/api/v1/attention/workflow_control/*/decisions',r=>{reviewed=true;return r.fulfill({json:{}})});
 let message=''; await page.route(`**/api/v1/runs/${runId}/messages`,r=>{message=r.request().postDataJSON().message;return r.fulfill({json:{id:'msg',status:'accepted'}})});
 await page.goto(`/work/${workId}/run/${runId}`);
 await expect(page.getByRole('button',{name:'Turns (3)',exact:true})).toBeVisible();
 await expect(page.getByText('3,200',{exact:true})).toBeVisible();
 await expect(page.getByText('The README now covers installation, workflows, and running the daemon.',{exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Verification',exact:true})).toBeVisible();
 await expect(page.getByRole('cell',{name:'Unit',exact:true})).toBeVisible();
 await expect(page.locator('a[href^="javascript:"]')).toHaveCount(0);
 await page.getByRole('combobox',{name:'Transcript format'}).selectOption('raw');
 await expect(page.getByRole('heading',{name:'Verification',exact:true})).toHaveCount(0);
 await expect(page.locator('.run-transcript-entry pre').filter({hasText:'## Verification'})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('combobox',{name:'Transcript format'})).toHaveValue('raw');
 await page.getByRole('combobox',{name:'Transcript format'}).selectOption('rendered');
 await page.getByRole('button',{name:'Timeline range end',exact:true}).focus(); for(let i=0;i<40;i++)await page.keyboard.press('ArrowLeft');
 await expect(page.getByText('The README now covers installation, workflows, and running the daemon.',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Reset range'}).click();
 await page.getByRole('button',{name:'Turns (3)',exact:true}).click(); await expect(page.getByRole('heading',{name:/Turn 1/})).toBeVisible();
 await page.getByRole('button',{name:'Artifacts',exact:true}).click(); await expect(page.getByRole('heading',{name:'DARKSTAR',exact:true})).toBeVisible(); await expect(page.getByRole('heading',{name:/Decisions/})).toBeVisible(); await expect(page.getByRole('heading',{name:/Open items/})).toBeVisible();
 await page.getByRole('button',{name:'Approve and continue'}).click(); await expect.poll(()=>reviewed).toBe(true);
 await page.getByRole('button',{name:'Terminal',exact:true}).click(); await page.getByRole('textbox',{name:'Message the agent'}).fill('Also document Windows setup.'); await page.getByRole('button',{name:'Send message to agent'}).click(); await expect.poll(()=>message).toBe('Also document Windows setup.');
 await page.screenshot({path:testInfo.outputPath('run-terminal.png'),fullPage:true});
 await page.reload(); await expect(page.getByRole('button',{name:'Turns (3)',exact:true})).toBeVisible();
});


test('timeline follows its right edge while historical selections remain fixed', async ({page}) => {
  await installEmptyControlPlane(page);
  const start='2026-09-08T17:00:00Z', workId='work_live_edge', runId='run_live_edge';
  const run={id:runId,workItemId:workId,workflowId:'test',workflowVersion:'1',status:'running',resourceVersion:1,createdAt:start,updatedAt:'2026-09-08T17:01:00Z'};
  const view={run,nodes:[],attempts:[],timeline:[],commands:[],timelinePageInfo:{hasEarlier:false},commandsPageInfo:{hasEarlier:false}};
  const event=(position:number,label:string)=>({position,time:new Date(Date.parse(start)+position*1000).toISOString(),kind:'attempt.provider_event',subject:'attempt',data:{payload:{providerMethod:'item/completed',params:{item:{type:'agentMessage',id:'message-'+position,text:label}}}}});
  const events=[event(10,'First message')];
  await page.route('**/api/v1/runs/'+runId,r=>r.fulfill({json:view}));
  await page.route('**/api/v1/work-items/'+workId,r=>r.fulfill({json:{work:{id:workId,title:'Live timeline',status:'in_progress',resourceVersion:1,createdAt:start,updatedAt:start},runs:[run],stories:[]}}));
  await page.route('**/api/v1/work-items/*/transition-plan**',r=>r.fulfill({json:{resourceVersion:1,state:'running',targets:[]}}));
  await page.route('**/api/v1/runs/'+runId+'/transcript?**',r=>r.fulfill({json:{events:events.filter(e=>e.position>Number(new URL(r.request().url()).searchParams.get('after')??0)),next:events.at(-1)!.position,hasMore:false}}));
  await page.goto('/work/'+workId+'/run/'+runId);
  await expect(page.getByText('First message',{exact:true})).toBeVisible();
  const endHandle=page.getByRole('button',{name:'Timeline range end',exact:true});
  await endHandle.focus(); await page.keyboard.press('ArrowLeft');
  events.push(event(70,'Outside fixed selection'));
  await expect(page.locator('.run-timeline-times')).toContainText('17:01:10');
  await expect(page.getByText('Outside fixed selection',{exact:true})).toHaveCount(0);
  const rail=await page.locator('.run-timeline-rail').boundingBox();
  if(!rail)throw new Error('Timeline missing');
  const dragEndToLive=async()=>{const handle=await endHandle.boundingBox();if(!handle)throw new Error('Handle missing');await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(rail.x+rail.width+2,handle.y+handle.height/2);await page.mouse.up();};
  await dragEndToLive();
  await expect(page.getByRole('button',{name:'Follow live',exact:true})).toHaveAttribute('aria-pressed','true');
  events.push(event(80,'New full-range message'));
  await expect(page.getByText('New full-range message',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Timeline range start',exact:true}).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('button',{name:'Follow live',exact:true})).toHaveAttribute('aria-pressed','true');
  events.push(event(90,'New narrowed live message'));
  await expect(page.getByText('New narrowed live message',{exact:true})).toBeVisible();
  await endHandle.focus(); await page.keyboard.press('ArrowLeft');
  events.push(event(100,'Later historical exclusion'));
  await expect(page.locator('.run-timeline-times')).toContainText('17:01:40');
  await expect(page.getByText('Later historical exclusion',{exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Follow live',exact:true}).click();
  await expect(page.getByText('Later historical exclusion',{exact:true})).toBeVisible();
});
