import { expect, test } from "@playwright/test";
import { installEmptyControlPlane } from "./acceptance.fixtures";

const digest=(value:string)=>value.repeat(64);
const document={apiVersion:"darkstar.local/v1alpha3",kind:"Workflow",metadata:{name:"darkstar/example",version:"1.0.0"},spec:{inputs:{task:{type:"task",resource:{kind:"task"}},design_template:{type:"template",resource:{kind:"template",version:"1.0.0",content:"# Design\n## Approach",requiredHeadings:["Approach"]}}},routeDefaults:{entry:"design",terminals:["design"]},nodes:{design:{type:"reasoning",displayName:"Design",entry:true,terminal:true,inputs:{task:{type:"task",from:"run.input.task"},template:{type:"template",from:"run.input.design_template"}},outputs:{design:{type:"markdown",artifact:{filename:"design.md",templateInput:"template"}}},reasoning:{agent:"designer",instructions:"Design the requested solution."},transitions:[]}}}};

test("published canvas versions preserve identity, edit typed resources, and publish the new version",async({page},testInfo)=>{
 await page.setViewportSize({width:1600,height:1000});await installEmptyControlPlane(page);
 const shipped={name:document.metadata.name,version:"1.0.0",digest:digest("a"),sourceScope:"default",sourceReference:"shipped",installedAt:"2026-09-08T00:00:00Z"};
 let versions:any[]=[shipped],draft:any;let duplicate:any;const saves:any[]=[];
 await page.route("**/api/v1/workflows/library",route=>route.fulfill({json:{versions,drafts:draft?[draft]:[],archives:[]}}));
 await page.route("**/api/v1/workflows/show?**",route=>{const version=versions.find(v=>v.version===new URL(route.request().url()).searchParams.get("version"))??shipped;return route.fulfill({json:{version,document:version.version==="1.0.0"?document:{...draft.document,metadata:{...draft.document.metadata,version:version.version}}}});});
 await page.route("**/api/v1/workflows/drafts/duplicate",async route=>{duplicate=route.request().postDataJSON();draft={id:"draft_version",name:duplicate.newName,scope:"user",scopeReference:"local-user",baseVersion:"1.0.0",revision:1,document:structuredClone(document),layout:{},documentDigest:digest("b"),updatedAt:"2026-09-08T00:00:00Z"};await route.fulfill({json:draft});});
 await page.route("**/api/v1/workflows/drafts/update",async route=>{const body=route.request().postDataJSON();saves.push(body);if(body.expectedRevision!==draft.revision)return route.fulfill({status:409,json:{code:"conflict",message:"stale revision"}});draft={...draft,...body,revision:draft.revision+1,documentDigest:digest("c")};await route.fulfill({json:draft});});
 await page.route("**/api/v1/workflows/drafts/validate",route=>route.fulfill({json:{draftId:draft.id,revision:draft.revision,documentDigest:draft.documentDigest,digest:digest("f"),findings:[]}}));
 await page.route("**/api/v1/workflows/drafts/publish",async route=>{const body=route.request().postDataJSON();const published={...shipped,version:body.version,digest:digest("e"),sourceScope:"user",sourceReference:"local-user"};versions=[shipped,published];await route.fulfill({json:{draftId:draft.id,draftRevision:draft.revision,sourceValidationDigest:digest("f"),disposition:"created",published}});});
 await page.goto("/workflows");await expect(page.getByText("Read only · create a new version to edit")).toBeVisible();
 await expect(page.locator(".workflow-editor-left")).toHaveCount(0);await expect(page.getByRole("tab")).toHaveCount(0);await expect(page.getByRole("complementary",{name:"Contextual inspector"})).toHaveCount(0);
 await page.getByRole("button",{name:"Zoom to fit"}).click();
 await expect(page.locator('.react-flow__node[data-id="$start"]')).toBeVisible();
 const typeColor=async(id:string)=>page.locator('.react-flow__node[data-id="'+id+'"] .react-flow__handle.source').evaluate(el=>getComputedStyle(el).backgroundColor);
 expect(await typeColor("$input:design_template")).not.toBe(await typeColor("$output:design:design"));
 await expect(page.locator('.react-flow__node[data-id="$input:design_template"] small')).toHaveText("template");
 await page.screenshot({path:testInfo.outputPath("published-canvas.png")});
 await page.getByRole("button",{name:"New version",exact:true}).click();await expect.poll(()=>duplicate?.newName).toBe("darkstar/example");
 await expect(page.getByText("Draft",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Zoom to fit"}).click();
 await page.locator('.react-flow__node[data-id="design"] .workflow-flow-node__body').click();await expect(page.getByText("Unsupported node",{exact:true})).toHaveCount(0);await expect(page.getByRole("complementary",{name:"Contextual inspector"})).toContainText("Instructions");await page.keyboard.press("Escape");

 const snap=page.getByRole("button",{name:"Snap to grid",exact:true});await expect(snap).toHaveAttribute("aria-pressed","false");await snap.click();await expect.poll(()=>saves.at(-1)?.layout.snapToGrid).toBe(true);
 const dragNode=page.locator('.react-flow__node[data-id="design"]');const box=await dragNode.boundingBox();if(!box)throw new Error("Missing design node");
 await page.mouse.move(box.x+box.width/2,box.y+16);await page.mouse.down();await page.mouse.move(box.x+box.width/2+93,box.y+79,{steps:12});await page.mouse.up();
 await expect.poll(()=>saves.at(-1)?.layout.nodes.design?.x % 22).toBe(0);await expect.poll(()=>saves.at(-1)?.layout.nodes.design?.y % 22).toBe(0);
 await snap.click();await expect.poll(()=>saves.at(-1)?.layout.snapToGrid).toBe(false);await expect(snap).toHaveAttribute("aria-pressed","false");
 await page.locator('.react-flow__node[data-id="$input:design_template"] .workflow-flow-node__body').click();
 await page.getByRole("textbox",{name:"Template",exact:true}).fill("# Design\n## Approach\nExplain alternatives.");await page.getByRole("button",{name:"Apply",exact:true}).click();
 await expect.poll(()=>saves.at(-1)?.document.spec.inputs.design_template.resource.content).toContain("Explain alternatives");
 await page.keyboard.press("Escape");await expect(page.getByRole("complementary",{name:"Contextual inspector"})).toHaveCount(0);
 const canvas=page.locator(".workflow-canvas");
 await canvas.focus();await page.keyboard.press("Insert");await page.getByRole("dialog",{name:"Add node"}).getByRole("button",{name:"Markdown file",exact:true}).click();
 const filenameDialog=page.getByRole("dialog",{name:"New Markdown file"});await expect(filenameDialog.getByRole("button",{name:"Add Markdown file"})).toBeDisabled();
 await filenameDialog.getByRole("textbox",{name:"Filename"}).fill("folder/design.md");await expect(filenameDialog.getByRole("button",{name:"Add Markdown file"})).toBeDisabled();
 await filenameDialog.getByRole("textbox",{name:"Filename"}).fill("notes.md");await filenameDialog.getByRole("button",{name:"Add Markdown file"}).click();
 await expect.poll(()=>saves.at(-1)?.document.spec.inputs.artifact?.resource.filename).toBe("notes.md");
 await page.keyboard.press("Escape");
await canvas.focus();await page.keyboard.press("Insert");await page.getByRole("dialog",{name:"Add node"}).getByRole("button",{name:"constant",exact:true}).click();
 await page.getByRole("combobox",{name:"Value type",exact:true}).selectOption("schema:record");await page.getByLabel("Schema name",{exact:true}).fill("readiness");await page.getByLabel("JSON Schema",{exact:true}).fill(JSON.stringify({type:"object",properties:{ready:{type:"boolean"}},required:["ready"],additionalProperties:false}));await page.getByLabel("Value (JSON)").fill('{"ready":true}');await page.getByRole("button",{name:"Apply",exact:true}).click();
 await expect.poll(()=>saves.at(-1)?.document.spec.inputs.constant?.resource.value.ready).toBe(true);
 await page.getByRole("button",{name:"Zoom to fit"}).click();
 await page.locator('.react-flow__node[data-id="$input:constant"] .workflow-flow-port--output').click();
 await page.locator('.react-flow__node[data-id="design"] button').filter({hasText:"+ Input"}).click();
 await expect.poll(()=>saves.at(-1)?.document.spec.nodes.design.inputs.constant?.from).toBe("run.input.constant");
 await expect(page.getByRole("button",{name:"Validate",exact:true})).toBeEnabled();await page.getByRole("button",{name:"Validate",exact:true}).click();
 await expect(page.getByRole("button",{name:"Publish version",exact:true})).toBeEnabled();await page.getByRole("button",{name:"Publish version",exact:true}).click();
 await page.getByRole("button",{name:"Publish exact revision"}).click();await expect(page.getByText("Read only · create a new version to edit")).toBeVisible();
 expect(versions.at(-1).version).toBe("1.0.1");expect(document.spec.inputs.design_template.resource.content).toBe("# Design\n## Approach");
 await page.screenshot({path:testInfo.outputPath("versioned-canvas.png")});
});
