/* This file is generated by dashboard/scripts/generate-api-client.mjs. */
/* Source: schemas/openapi-v1alpha1.json. Do not edit by hand. */

export interface components {
  schemas: {
    "ApiError": unknown;
    "RecoveryStatus": { "reconciled": number; "reconcileRequired": number; };
    "Health": { "schemaVersion": 1; "status": "ok"; "apiVersions": Array<"v1">; "recovery"?: components["schemas"]["RecoveryStatus"]; };
    "ApiRoot": { "schemaVersion": 1; "apiVersion": "v1"; "recovery"?: components["schemas"]["RecoveryStatus"]; };
    "DoctorReport": unknown;
    "ProjectRegistration": { "name": string; "source": string; };
    "Project": { "id": string; "name": string; "sourceHash": string; "status": "active" | "archived"; "resourceVersion": number; "lastGlobalPosition": number; "createdAt": string; "updatedAt": string; };
    "ProjectView": { "schemaVersion": 1; "project": components["schemas"]["Project"]; "workItems": Array<components["schemas"]["WorkItem"]>; };
    "CreateWorkItemRequest": { "projectId": string; "title": string; "priority"?: number; };
    "ImportWorkItemRequest": { "projectId": string; "sourceReference": string; "title"?: string; "priority"?: number; };
    "WorkItem": { "id": string; "projectId": string; "title": string; "sourceHash": string; "priority": number; "status": "open" | "active" | "completed" | "cancelled"; "resourceVersion": number; "lastGlobalPosition": number; "createdAt": string; "updatedAt": string; };
    "WorkItemView": { "schemaVersion": 1; "work": components["schemas"]["WorkItem"]; "runs": Array<components["schemas"]["Run"]>; "stories": Array<{  }>; };
    "WorkflowDocument": unknown | unknown;
    "WorkflowVersionSummary": { "name": string; "version": string; "digest": string; "sourceScope": "default" | "user" | "project"; "sourceReference": string; "installedAt": string; };
    "WorkflowCandidateRequest": { "document": components["schemas"]["WorkflowDocument"]; "sourceScope": "default" | "user" | "project"; "sourceReference": string; };
    "WorkflowValidationIssue": { "code": string; "message": string; "location"?: string; "details"?: { [key: string]: Array<string>; }; };
    "WorkflowValidationReport": { "metadata"?: { "name": string; "version": string; "displayName"?: string; "description"?: string; }; "digest"?: string; "issues": Array<components["schemas"]["WorkflowValidationIssue"]>; };
    "WorkflowInstallResult": { "version": components["schemas"]["WorkflowVersionSummary"]; "disposition": "created" | "already_installed"; };
    "WorkflowDefinition": { "version": components["schemas"]["WorkflowVersionSummary"]; "document": components["schemas"]["WorkflowDocument"]; };
    "WorkflowIdentity": { "name": string; "version": string; "digest": string; };
    "WorkflowGraph": { "workflow": components["schemas"]["WorkflowIdentity"]; "nodes": Array<{ "id": string; "type": "reasoning" | "gate" | "command" | "approval" | "subworkflow" | "point_execution"; "entry"?: boolean; "terminal"?: boolean; }>; "edges": Array<{ "id": string; "from": string; "to": string; }>; };
    "WorkflowPreviewRequest": { "range": { "from"?: string; "until"?: Array<string>; }; "context": { "runInputs"?: { [key: string]: unknown; }; "acceptedOutputs"?: { [key: string]: unknown; }; "requiredNodes"?: Array<string>; }; };
    "WorkflowRoutePreview": { "workflow": components["schemas"]["WorkflowIdentity"]; "route": components["schemas"]["FrozenRoute"]; };
    "Artifact": unknown;
    "ArtifactRepresentation": unknown;
    "ArtifactBinding": unknown;
    "ArtifactImpactAssessment": unknown;
    "ArtifactTargetKind": "project" | "work" | "run" | "node" | "checkpoint" | "decision" | "story" | "implementation_point";
    "ArtifactVersionRef": { "artifactId": string; "version": number; };
    "ArtifactTarget": { "kind": components["schemas"]["ArtifactTargetKind"]; "id": string; };
    "ArtifactIngestRequest": { "artifactId"?: string; "sourceKind": "file" | "paste" | "stdin" | "generated" | "external"; "sourceName": string; "mediaType": string; "content": string; "sensitivity"?: "unknown" | "public" | "internal" | "sensitive" | "secret"; "creator"?: string; "roles"?: Array<string>; "tags"?: Array<string>; };
    "ArtifactIngestResult": { "artifact": components["schemas"]["Artifact"]; "created": boolean; "duplicateOf"?: components["schemas"]["ArtifactVersionRef"]; "capability": {  }; "diagnostics": Array<string>; };
    "ArtifactView": { "artifact": components["schemas"]["Artifact"]; "freshness": "current" | "stale" | "invalid"; "representations": Array<components["schemas"]["ArtifactRepresentation"]>; };
    "ArtifactAttachRequest": { "bindingId"?: string; "artifact": components["schemas"]["ArtifactVersionRef"]; "target": components["schemas"]["ArtifactTarget"]; };
    "ArtifactImpactRequest": { "target": components["schemas"]["ArtifactTarget"]; "runId"?: string; };
    "ArtifactLintResult": { "artifact": components["schemas"]["ArtifactVersionRef"]; "valid": boolean; "issues": Array<{ "code": string; "message": string; }>; };
    "ArtifactVersionDiff": { "artifactId": string; "from": number; "to": number; "changed": Array<"content" | "mediaType" | "sensitivity" | "roles" | "tags">; "fromDigest": string; "toDigest": string; "representations": { "from": Array<string>; "to": Array<string>; }; };
    "RunExportManifest": unknown;
    "CreateRunRequest": { "workItemId": string; "workflowId": string; "workflowVersion": string; };
    "StartFakeRunRequest": { "scenario": "fake-success" | "fake-restart"; };
    "RetryRunRequest": { "nodeId"?: string; };
    "ContinueRunRequest": { "until": string; };
    "ReadinessEvidence": { "source": string; "observation": string; };
    "ReadinessScore": { "name": string; "value": number; "evidence": Array<components["schemas"]["ReadinessEvidence"]>; };
    "ReadinessInformationFinding": { "level": "information"; "code": string; "summary": string; "evidence": Array<components["schemas"]["ReadinessEvidence"]>; };
    "ReadinessRecommendationFinding": { "level": "recommendation"; "code": string; "summary": string; "evidence": Array<components["schemas"]["ReadinessEvidence"]>; "remedyCode": string; };
    "ReadinessPolicyGateFinding": { "level": "policy_gate"; "code": string; "summary": string; "evidence": Array<components["schemas"]["ReadinessEvidence"]>; "policy": string; "status": "satisfied" | "unsatisfied"; "remedyCode"?: string; };
    "ReadinessInvariantFinding": { "level": "invariant"; "code": string; "summary": string; "evidence": Array<components["schemas"]["ReadinessEvidence"]>; "invariant": string; "status": "upheld" | "violated"; "remedyCode"?: string; };
    "ReadinessFinding": components["schemas"]["ReadinessInformationFinding"] | components["schemas"]["ReadinessRecommendationFinding"] | components["schemas"]["ReadinessPolicyGateFinding"] | components["schemas"]["ReadinessInvariantFinding"];
    "ReadinessRemedy": { "code": string; "target": string; "action": "supply_input" | "revise_artifact" | "clarify_decision" | "install_capability" | "rerun_validation"; "description": string; };
    "ReadinessRouteImpact": { "addedNodes"?: Array<string>; "removedNodes"?: Array<string>; "addedTransitions"?: Array<string>; "removedTransitions"?: Array<string>; "previousTerminals": Array<string>; "proposedTerminals": Array<string>; };
    "ReadinessRouteState": { "runId": string; "revision": number; "route": components["schemas"]["FrozenRoute"]; "overrides"?: Array<{ "transitionId": string; "enabled": boolean; }>; };
    "ReadinessRouteChange": { "patchId": string; "reason": string; "impact": components["schemas"]["ReadinessRouteImpact"]; "candidate": components["schemas"]["ReadinessRouteState"]; "authorizationMode": "require_approval"; "scopeDigest": string; "validationDigest": string; "policyDigest": string; };
    "ReadinessAssessment": { "assessmentId": string; "runId": string; "nodeId": string; "scores": Array<components["schemas"]["ReadinessScore"]>; "findings": Array<components["schemas"]["ReadinessFinding"]>; "remedies": Array<components["schemas"]["ReadinessRemedy"]>; "disposition": "ready" | "choice_required" | "policy_blocked" | "invariant_blocked"; "digest": string; "routeChange"?: components["schemas"]["ReadinessRouteChange"]; };
    "ReadinessAllowedAction": { "choice": "continue"; } | { "choice": "accept_route_change"; } | { "choice": "supply_input"; "remedy": components["schemas"]["ReadinessRemedy"]; } | { "choice": "cancel"; };
    "ReadinessActor": { "type": "user" | "external"; "id": string; };
    "ReadinessDecision": { "decisionId": string; "choice": "continue" | "accept_route_change" | "supply_input" | "cancel"; "remedyCode"?: string; "reason": string; "effectStatus": "pending"; "actor": components["schemas"]["ReadinessActor"]; "decidedAt": string; };
    "RunReadinessView": { "assessment": components["schemas"]["ReadinessAssessment"]; "status": "pending" | "decided"; "allowedActions": Array<components["schemas"]["ReadinessAllowedAction"]>; "decision"?: components["schemas"]["ReadinessDecision"]; "resourceVersion": number; "createdAt": string; "updatedAt": string; };
    "ReadinessDecisionRequest": { "action": "continue" | "accept_route_change" | "cancel"; "assessmentDigest": string; "reason": string; } | { "action": "supply_input"; "assessmentDigest": string; "reason": string; "remedyCode": string; };
    "FrozenRouteNode": { "id": string; "join"?: {  }; };
    "FrozenRouteTransition": { "id": string; "from": string; "to": string; };
    "FrozenRouteExcludedNode": { "id": string; "reason": "before_entry" | "past_terminal" | "not_connected"; };
    "FrozenRouteInputRequirement": { "code": string; "node": string; "input": string; "source": string; };
    "FrozenRoute": { "entry": string; "terminals": Array<string>; "nodes": Array<components["schemas"]["FrozenRouteNode"]>; "transitions": Array<components["schemas"]["FrozenRouteTransition"]>; "excludedNodes": Array<components["schemas"]["FrozenRouteExcludedNode"]>; "inputRequirements": Array<components["schemas"]["FrozenRouteInputRequirement"]>; };
    "Run": { "id": string; "workItemId": string; "workflowId": string; "workflowVersion": string; "workflowDigest"?: string; "routeDigest"?: string; "routeSnapshot"?: components["schemas"]["FrozenRoute"]; "priority"?: number; "status": "pending" | "draft" | "ready" | "queued" | "running" | "waiting" | "blocked" | "completed" | "failed" | "cancelled" | "reconcile_required"; "resourceVersion": number; "lastGlobalPosition"?: number; "createdAt": string; "updatedAt": string; };
    "Attempt": { "id": string; "runId": string; "visitId"?: string; "nodeId"?: string; "pointId"?: string; "pointRevision"?: number; "priority"?: number; "scenario": string; "provider": string; "status": "created" | "starting" | "running" | "validating" | "succeeded" | "failed" | "cancelled" | "interrupted" | "reconcile_required"; "providerThreadId"?: string; "providerTurnId"?: string; "processOwnerId"?: string; "lastSequence": number; "logReference"?: string; "resourceVersion": number; "lastGlobalPosition": number; "createdAt": string; "updatedAt": string; };
    "NodeVisit": { "id": string; "runId": string; "nodeId": string; "status": "pending" | "ready" | "running" | "validating" | "waiting_checkpoint" | "succeeded" | "rejected" | "failed" | "cancelled"; "resourceVersion": number; "lastGlobalPosition": number; "createdAt": string; "updatedAt": string; };
    "RunTimelineEntry": { "id": string; "globalPosition": number; "aggregateType": "project" | "work" | "story" | "point" | "run" | "visit" | "attempt" | "artifact" | "approval" | "operation" | "assessment"; "aggregateId": string; "aggregateRevision": number; "kind": string; "occurredAt": string; "recordedAt": string; "actorType": "user" | "system" | "provider" | "external"; };
    "RunTimelinePageInfo": { "hasEarlier": boolean; "firstPosition"?: number; "lastPosition"?: number; };
    "RunCommandSummary": { "scope": string; "status": string; "responseStatus"?: number; "firstEventPosition"?: number; "lastEventPosition"?: number; "createdAt": string; "completedAt"?: string; };
    "RunCommandPageInfo": { "hasEarlier": boolean; };
    "RunView": { "schemaVersion": 1; "run": components["schemas"]["Run"]; "nodes": Array<components["schemas"]["NodeVisit"]>; "attempts": Array<components["schemas"]["Attempt"]>; "timeline": Array<components["schemas"]["RunTimelineEntry"]>; "timelinePageInfo": components["schemas"]["RunTimelinePageInfo"]; "commands": Array<components["schemas"]["RunCommandSummary"]>; "commandsPageInfo": components["schemas"]["RunCommandPageInfo"]; };
    "RunPage": { "items": Array<components["schemas"]["Run"]>; "pageInfo": { "nextCursor": string | null; }; };
  };
}

export interface ApiOperations {
    "getHealth": { method: "GET"; path: "/api/v1/health"; response: components["schemas"]["Health"]; body: never; };
    "getApiRoot": { method: "GET"; path: "/api/v1/"; response: components["schemas"]["ApiRoot"]; body: never; };
    "getDoctorReport": { method: "GET"; path: "/api/v1/doctor"; response: components["schemas"]["DoctorReport"]; body: never; };
    "listProjects": { method: "GET"; path: "/api/v1/projects"; response: Array<components["schemas"]["Project"]>; body: never; };
    "registerProject": { method: "POST"; path: "/api/v1/projects"; response: components["schemas"]["Project"]; body: components["schemas"]["ProjectRegistration"]; };
    "getProject": { method: "GET"; path: "/api/v1/projects/{projectId}"; response: components["schemas"]["ProjectView"]; body: never; };
    "listWorkItems": { method: "GET"; path: "/api/v1/work-items"; response: Array<components["schemas"]["WorkItem"]>; body: never; };
    "createWorkItem": { method: "POST"; path: "/api/v1/work-items"; response: components["schemas"]["WorkItem"]; body: components["schemas"]["CreateWorkItemRequest"]; };
    "importWorkItem": { method: "POST"; path: "/api/v1/work-items/import"; response: components["schemas"]["WorkItem"]; body: components["schemas"]["ImportWorkItemRequest"]; };
    "getWorkItem": { method: "GET"; path: "/api/v1/work-items/{workItemId}"; response: components["schemas"]["WorkItemView"]; body: never; };
    "listRuns": { method: "GET"; path: "/api/v1/runs"; response: components["schemas"]["RunPage"]; body: never; };
    "createOrStartRun": { method: "POST"; path: "/api/v1/runs"; response: components["schemas"]["Run"]; body: components["schemas"]["CreateRunRequest"] | components["schemas"]["StartFakeRunRequest"]; };
    "getRun": { method: "GET"; path: "/api/v1/runs/{runId}"; response: components["schemas"]["RunView"]; body: never; };
    "getRunReadiness": { method: "GET"; path: "/api/v1/runs/{runId}/readiness"; response: components["schemas"]["RunReadinessView"]; body: never; };
    "decideRunReadiness": { method: "POST"; path: "/api/v1/runs/{runId}/readiness/decisions"; response: components["schemas"]["RunReadinessView"]; body: components["schemas"]["ReadinessDecisionRequest"]; };
    "exportRun": { method: "GET"; path: "/api/v1/runs/{runId}/export"; response: string; body: never; };
    "cancelRun": { method: "POST"; path: "/api/v1/runs/{runId}/cancel"; response: components["schemas"]["Run"]; body: never; };
    "pauseRun": { method: "POST"; path: "/api/v1/runs/{runId}/pause"; response: components["schemas"]["Run"]; body: never; };
    "resumeRun": { method: "POST"; path: "/api/v1/runs/{runId}/resume"; response: components["schemas"]["Run"]; body: never; };
    "retryRun": { method: "POST"; path: "/api/v1/runs/{runId}/retry"; response: components["schemas"]["Run"]; body: components["schemas"]["RetryRunRequest"]; };
    "continueRun": { method: "POST"; path: "/api/v1/runs/{runId}/continue"; response: components["schemas"]["Run"]; body: components["schemas"]["ContinueRunRequest"]; };
    "decideApproval": { method: "POST"; path: "/api/v1/approvals/{approvalId}/decisions"; response: {  }; body: { "action": "approve" | "acknowledge" | "request_changes" | "reject" | "satisfy_external" | "deny" | "allow_once" | "allow_for_session" | "cancel" | "expire"; "scopeDigest": string; "policyDigest": string; "comment"?: string; }; };
    "streamEvents": { method: "GET"; path: "/api/v1/events"; response: string; body: never; };
    "readLog": { method: "GET"; path: "/api/v1/logs/{reference}"; response: string; body: never; };
    "listWorkflows": { method: "GET"; path: "/api/v1/workflows"; response: Array<components["schemas"]["WorkflowVersionSummary"]>; body: never; };
    "validateWorkflow": { method: "POST"; path: "/api/v1/workflows/validate"; response: components["schemas"]["WorkflowValidationReport"]; body: components["schemas"]["WorkflowCandidateRequest"]; };
    "installWorkflow": { method: "POST"; path: "/api/v1/workflows/install"; response: components["schemas"]["WorkflowInstallResult"]; body: components["schemas"]["WorkflowCandidateRequest"]; };
    "showWorkflow": { method: "GET"; path: "/api/v1/workflows/show"; response: components["schemas"]["WorkflowDefinition"]; body: never; };
    "graphWorkflow": { method: "GET"; path: "/api/v1/workflows/graph"; response: components["schemas"]["WorkflowGraph"]; body: never; };
    "previewWorkflowRoute": { method: "POST"; path: "/api/v1/workflows/preview"; response: components["schemas"]["WorkflowRoutePreview"]; body: components["schemas"]["WorkflowPreviewRequest"]; };
    "listArtifacts": { method: "GET"; path: "/api/v1/artifacts"; response: Array<components["schemas"]["ArtifactView"]>; body: never; };
    "ingestArtifact": { method: "POST"; path: "/api/v1/artifacts"; response: components["schemas"]["ArtifactIngestResult"]; body: components["schemas"]["ArtifactIngestRequest"]; };
    "getArtifact": { method: "GET"; path: "/api/v1/artifacts/{artifactId}"; response: components["schemas"]["ArtifactView"]; body: never; };
    "reviseArtifact": { method: "POST"; path: "/api/v1/artifacts/{artifactId}/revisions"; response: components["schemas"]["ArtifactIngestResult"]; body: components["schemas"]["ArtifactIngestRequest"]; };
    "diffArtifactVersions": { method: "GET"; path: "/api/v1/artifacts/{artifactId}/diff"; response: components["schemas"]["ArtifactVersionDiff"]; body: never; };
    "extractArtifact": { method: "POST"; path: "/api/v1/artifacts/{artifactId}/extract"; response: {  }; body: never; };
    "lintArtifact": { method: "GET"; path: "/api/v1/artifacts/{artifactId}/lint"; response: components["schemas"]["ArtifactLintResult"]; body: never; };
    "listArtifactRepresentations": { method: "GET"; path: "/api/v1/artifacts/{artifactId}/representations"; response: Array<components["schemas"]["ArtifactRepresentation"]>; body: never; };
    "assessArtifactImpact": { method: "POST"; path: "/api/v1/artifacts/{artifactId}/impact"; response: components["schemas"]["ArtifactImpactAssessment"]; body: components["schemas"]["ArtifactImpactRequest"]; };
    "attachArtifact": { method: "POST"; path: "/api/v1/artifact-bindings"; response: components["schemas"]["ArtifactBinding"]; body: components["schemas"]["ArtifactAttachRequest"]; };
    "detachArtifact": { method: "DELETE"; path: "/api/v1/artifact-bindings/{bindingId}"; response: components["schemas"]["ArtifactBinding"]; body: never; };
}

export type ApiOperationId = keyof ApiOperations;

export const operationDefinitions: Record<ApiOperationId, { method: string; path: string }> = {
  "getHealth": { method: "GET", path: "/api/v1/health" },
  "getApiRoot": { method: "GET", path: "/api/v1/" },
  "getDoctorReport": { method: "GET", path: "/api/v1/doctor" },
  "listProjects": { method: "GET", path: "/api/v1/projects" },
  "registerProject": { method: "POST", path: "/api/v1/projects" },
  "getProject": { method: "GET", path: "/api/v1/projects/{projectId}" },
  "listWorkItems": { method: "GET", path: "/api/v1/work-items" },
  "createWorkItem": { method: "POST", path: "/api/v1/work-items" },
  "importWorkItem": { method: "POST", path: "/api/v1/work-items/import" },
  "getWorkItem": { method: "GET", path: "/api/v1/work-items/{workItemId}" },
  "listRuns": { method: "GET", path: "/api/v1/runs" },
  "createOrStartRun": { method: "POST", path: "/api/v1/runs" },
  "getRun": { method: "GET", path: "/api/v1/runs/{runId}" },
  "getRunReadiness": { method: "GET", path: "/api/v1/runs/{runId}/readiness" },
  "decideRunReadiness": { method: "POST", path: "/api/v1/runs/{runId}/readiness/decisions" },
  "exportRun": { method: "GET", path: "/api/v1/runs/{runId}/export" },
  "cancelRun": { method: "POST", path: "/api/v1/runs/{runId}/cancel" },
  "pauseRun": { method: "POST", path: "/api/v1/runs/{runId}/pause" },
  "resumeRun": { method: "POST", path: "/api/v1/runs/{runId}/resume" },
  "retryRun": { method: "POST", path: "/api/v1/runs/{runId}/retry" },
  "continueRun": { method: "POST", path: "/api/v1/runs/{runId}/continue" },
  "decideApproval": { method: "POST", path: "/api/v1/approvals/{approvalId}/decisions" },
  "streamEvents": { method: "GET", path: "/api/v1/events" },
  "readLog": { method: "GET", path: "/api/v1/logs/{reference}" },
  "listWorkflows": { method: "GET", path: "/api/v1/workflows" },
  "validateWorkflow": { method: "POST", path: "/api/v1/workflows/validate" },
  "installWorkflow": { method: "POST", path: "/api/v1/workflows/install" },
  "showWorkflow": { method: "GET", path: "/api/v1/workflows/show" },
  "graphWorkflow": { method: "GET", path: "/api/v1/workflows/graph" },
  "previewWorkflowRoute": { method: "POST", path: "/api/v1/workflows/preview" },
  "listArtifacts": { method: "GET", path: "/api/v1/artifacts" },
  "ingestArtifact": { method: "POST", path: "/api/v1/artifacts" },
  "getArtifact": { method: "GET", path: "/api/v1/artifacts/{artifactId}" },
  "reviseArtifact": { method: "POST", path: "/api/v1/artifacts/{artifactId}/revisions" },
  "diffArtifactVersions": { method: "GET", path: "/api/v1/artifacts/{artifactId}/diff" },
  "extractArtifact": { method: "POST", path: "/api/v1/artifacts/{artifactId}/extract" },
  "lintArtifact": { method: "GET", path: "/api/v1/artifacts/{artifactId}/lint" },
  "listArtifactRepresentations": { method: "GET", path: "/api/v1/artifacts/{artifactId}/representations" },
  "assessArtifactImpact": { method: "POST", path: "/api/v1/artifacts/{artifactId}/impact" },
  "attachArtifact": { method: "POST", path: "/api/v1/artifact-bindings" },
  "detachArtifact": { method: "DELETE", path: "/api/v1/artifact-bindings/{bindingId}" },
};
