// Generated by packages/plugin-sdk/build.mjs; do not edit.
import { createInterface } from "node:readline";
const protocol = "darkstar.plugin/v1";
function serve(plugin) {
  const pending = /* @__PURE__ */ new Map();
  let sequence = 0;
  const send = (message) => {
    return process.stdout.write(JSON.stringify(message) + "\n");
  };
  const host = {
    call(method, arguments_) {
      const id = `host-${++sequence}`;
      return new Promise((resolve, reject) => {
        pending.set(id, {
          resolve,
          reject
        });
        send({
          type: "host_call",
          id,
          method,
          params: arguments_
        });
      });
    }
  };
  const lines = createInterface({
    input: process.stdin,
    crlfDelay: Infinity
  });
  lines.on("line", async (line) => {
    let request;
    try {
      request = JSON.parse(line);
      if (request.type === "host_result") {
        const waiter = pending.get(request.id);
        if (!waiter) {
          throw new Error("Unknown host result");
        }
        pending.delete(request.id);
        request.error ? waiter.reject(new Error(request.error)) : waiter.resolve(request.result);
        return;
      }
      if (request.type !== "request") {
        throw new Error("Invalid request type");
      }
      let result;
      if (request.method === "describe") {
        result = {
          protocol,
          ref: {
            id: plugin.id,
            version: plugin.version
          },
          resources: plugin.resources,
          tools: plugin.tools ?? [],
          ...plugin.nodes ? {
            nodes: plugin.nodes
          } : {}
        };
      } else {
        if (request.method === "invoke") {
          const tool = [...plugin.resources.map((resource) => {
            return resource.tool;
          }), ...plugin.tools ?? [], ...plugin.nodes ?? []].find((tool2) => {
            return tool2.id === request.params.contribution;
          });
          if (!tool) {
            throw new Error("Unknown contribution");
          }
          result = await tool.invoke(request.params.arguments, host);
        } else {
          throw new Error("Unknown method");
        }
      }
      send({
        type: "response",
        id: request.id,
        result
      });
    } catch (error) {
      send({
        type: "response",
        id: request?.id ?? "",
        error: error instanceof Error ? error.message : String(error)
      });
    }
  });
}
function journal(kind, id, createOperation, updateOperations) {
  const operations = ["read", createOperation, ...updateOperations];
  return {
    kind,
    createOperation,
    updateOperations,
    tool: {
      id,
      description: `Use this append-only ${kind} journal. Use entryId for an existing item; use an empty entryId to create one. key is a stable operation key, reused on retry. text records the item, decision, or resolution rationale.`,
      inputSchema: {
        type: "object",
        additionalProperties: false,
        properties: {
          operation: {
            type: "string",
            enum: operations
          },
          entryId: {
            type: "string"
          },
          text: {
            type: "string"
          },
          key: {
            type: "string"
          },
          expectedRevision: {
            type: "integer",
            minimum: 0
          }
        },
        required: ["operation"]
      },
      resultSchema: {
        oneOf: [{
          type: "object",
          additionalProperties: false,
          properties: {
            markdown: {
              type: "string"
            },
            revision: {
              type: "integer",
              minimum: 0
            }
          },
          required: ["markdown", "revision"]
        }, {
          type: "object",
          additionalProperties: false,
          properties: {
            entryId: {
              type: "string"
            },
            status: {
              enum: ["recorded", "already_recorded"]
            },
            revision: {
              type: "integer",
              minimum: 1
            }
          },
          required: ["entryId", "status", "revision"]
        }]
      },
      requiredCapabilities: ["journal.read", "journal.mutate"],
      async invoke(raw, host) {
        const args = raw;
        if (!operations.includes(args.operation)) {
          throw new Error("Unsupported journal operation");
        }
        if (args.operation === "read") {
          return host.call("journal.read", {});
        }
        if (!Number.isSafeInteger(args.expectedRevision) || args.expectedRevision < 0) {
          throw new Error("Mutation requires expectedRevision from the latest read");
        }
        if (!args.text?.trim() || !args.key?.trim()) {
          throw new Error("text and key are required");
        }
        if (args.operation === createOperation && args.entryId) {
          throw new Error("New entries cannot supply entryId");
        }
        if (args.operation !== createOperation && !args.entryId) {
          throw new Error("An existing entryId is required");
        }
        return host.call("journal.mutate", args);
      }
    }
  };
}
const content = {
  oneOf: [{
    type: "object",
    additionalProperties: false,
    properties: {
      encoding: {
        const: "utf8"
      },
      text: {
        type: "string"
      }
    },
    required: ["encoding", "text"]
  }, {
    type: "object",
    additionalProperties: false,
    properties: {
      encoding: {
        const: "base64"
      },
      data: {
        type: "string"
      }
    },
    required: ["encoding", "data"]
  }]
};
function workspaceTool(id, description, properties, resultProperties, required = Object.keys(properties)) {
  return {
    id,
    description,
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties,
      required
    },
    resultSchema: {
      type: "object",
      additionalProperties: false,
      properties: resultProperties,
      required: Object.keys(resultProperties)
    },
    requiredCapabilities: [id],
    invoke: (args, host) => {
      return host.call(id, args);
    }
  };
}
const area = {
  type: "string",
  enum: ["plugin_state", "scratch", "staged"]
};
const path = {
  type: "string",
  minLength: 1
};
const digest = {
  type: "string",
  pattern: "^[a-f0-9]{64}$"
};
serve({
  id: "darkstar/builtin-resources",
  version: "1.0.0",
  tools: [workspaceTool("workspace.read", "Read a file and its current digest in this plugin\u2019s work-item workspace.", {
    area,
    path
  }, {
    content,
    digest
  }), workspaceTool("workspace.write", "Create a file, or replace it by supplying expectedDigest from the latest read. Published artifact revisions remain immutable.", {
    area,
    path,
    content,
    expectedDigest: digest
  }, {
    status: {
      const: "stored"
    },
    size: {
      type: "integer",
      minimum: 0
    },
    digest
  }, ["area", "path", "content"]), workspaceTool("workspace.publish_artifact", "Publish a staged file as an immutable artifact. This does not submit a workflow output or grant approval.", {
    path,
    mediaType: {
      type: "string",
      minLength: 1
    },
    key: {
      type: "string",
      minLength: 1
    }
  }, {
    artifact: {
      type: "object",
      additionalProperties: false,
      properties: {
        artifactId: {
          type: "string",
          minLength: 1
        },
        version: {
          type: "integer",
          minimum: 1
        }
      },
      required: ["artifactId", "version"]
    },
    digest,
    mediaType: {
      type: "string"
    }
  })],
  resources: [journal("open_items", "darkstar/open-items", "add", ["resolve", "defer"]), journal("decision_log", "darkstar/decision-log", "record", ["supersede"])]
});
export {
  protocol,
  serve
};
